"""Golden fixtures for mobile-critical content API response contracts."""

from __future__ import annotations

import pytest

from app.models.api.common import ContentDetailResponse, ContentSummaryResponse, DetectedFeed
from app.models.contracts import (
    ContentClassification,
    ContentStatus,
    ContentType,
    SummaryKind,
    SummaryVersion,
)


def _dump(response: ContentSummaryResponse | ContentDetailResponse) -> dict[str, object]:
    return response.model_dump(mode="json")


@pytest.mark.parametrize(
    ("response", "expected"),
    [
        (
            ContentSummaryResponse(
                id=101,
                content_type=ContentType.ARTICLE,
                url="https://example.com/article",
                source_url="https://m.example.com/article",
                discussion_url="https://news.ycombinator.com/item?id=101",
                title="Example Article",
                source="Example",
                platform="web",
                status=ContentStatus.COMPLETED,
                short_summary="A concise article summary.",
                created_at="2026-04-27T12:00:00Z",
                processed_at="2026-04-27T12:03:00Z",
                classification=ContentClassification.TO_READ,
                publication_date="2026-04-26T10:00:00Z",
                is_read=False,
                is_saved_to_knowledge=True,
                image_url="/static/images/content/101.png",
                thumbnail_url="/static/images/thumbnails/101.png",
                primary_topic="AI",
                top_comment={"author": "alice", "text": "Useful context."},
                comment_count=12,
            ),
            {
                "id": 101,
                "content_type": "article",
                "url": "https://example.com/article",
                "source_url": "https://m.example.com/article",
                "discussion_url": "https://news.ycombinator.com/item?id=101",
                "title": "Example Article",
                "source": "Example",
                "platform": "web",
                "status": "completed",
                "short_summary": "A concise article summary.",
                "created_at": "2026-04-27T12:00:00Z",
                "processed_at": "2026-04-27T12:03:00Z",
                "classification": "to_read",
                "publication_date": "2026-04-26T10:00:00Z",
                "is_read": False,
                "is_saved_to_knowledge": True,
                "news_article_url": None,
                "news_discussion_url": None,
                "news_key_points": None,
                "news_summary": None,
                "user_status": None,
                "image_url": "/static/images/content/101.png",
                "thumbnail_url": "/static/images/thumbnails/101.png",
                "primary_topic": "AI",
                "top_comment": {"author": "alice", "text": "Useful context."},
                "comment_count": 12,
            },
        ),
        (
            ContentSummaryResponse(
                id=202,
                content_type=ContentType.PODCAST,
                url="https://podcasts.example.com/episodes/202",
                title="Example Podcast Episode",
                source="Example Podcast",
                platform="podcast_rss",
                status=ContentStatus.AWAITING_IMAGE,
                short_summary="The episode summary.",
                created_at="2026-04-27T13:00:00Z",
                processed_at=None,
                classification=ContentClassification.TO_READ,
                is_read=True,
                primary_topic="Startups",
            ),
            {
                "id": 202,
                "content_type": "podcast",
                "url": "https://podcasts.example.com/episodes/202",
                "source_url": None,
                "discussion_url": None,
                "title": "Example Podcast Episode",
                "source": "Example Podcast",
                "platform": "podcast_rss",
                "status": "awaiting_image",
                "short_summary": "The episode summary.",
                "created_at": "2026-04-27T13:00:00Z",
                "processed_at": None,
                "classification": "to_read",
                "publication_date": None,
                "is_read": True,
                "is_saved_to_knowledge": False,
                "news_article_url": None,
                "news_discussion_url": None,
                "news_key_points": None,
                "news_summary": None,
                "user_status": None,
                "image_url": None,
                "thumbnail_url": None,
                "primary_topic": "Startups",
                "top_comment": None,
                "comment_count": None,
            },
        ),
        (
            ContentSummaryResponse(
                id=303,
                content_type=ContentType.NEWS,
                url="https://news.example.com/items/303",
                title="Fast News Item",
                source="SciURLs",
                platform="aggregator",
                status=ContentStatus.COMPLETED,
                short_summary="A short news item.",
                created_at="2026-04-27T14:00:00Z",
                news_article_url="https://publisher.example.com/story",
                news_discussion_url="https://news.example.com/discuss/303",
                news_key_points=["Point one", "Point two"],
                news_summary="A brief synthesized news overview.",
                user_status="inbox",
            ),
            {
                "id": 303,
                "content_type": "news",
                "url": "https://news.example.com/items/303",
                "source_url": None,
                "discussion_url": None,
                "title": "Fast News Item",
                "source": "SciURLs",
                "platform": "aggregator",
                "status": "completed",
                "short_summary": "A short news item.",
                "created_at": "2026-04-27T14:00:00Z",
                "processed_at": None,
                "classification": None,
                "publication_date": None,
                "is_read": False,
                "is_saved_to_knowledge": False,
                "news_article_url": "https://publisher.example.com/story",
                "news_discussion_url": "https://news.example.com/discuss/303",
                "news_key_points": ["Point one", "Point two"],
                "news_summary": "A brief synthesized news overview.",
                "user_status": "inbox",
                "image_url": None,
                "thumbnail_url": None,
                "primary_topic": None,
                "top_comment": None,
                "comment_count": None,
            },
        ),
    ],
)
def test_content_summary_response_contract(
    response: ContentSummaryResponse,
    expected: dict[str, object],
) -> None:
    assert _dump(response) == expected


@pytest.mark.parametrize(
    ("response", "expected"),
    [
        (
            ContentDetailResponse(
                id=401,
                content_type=ContentType.ARTICLE,
                url="https://example.com/long-read",
                source_url="https://m.example.com/long-read",
                discussion_url="https://news.ycombinator.com/item?id=401",
                title="Long Read",
                display_title="Structured Long Read",
                source="Example",
                status=ContentStatus.COMPLETED,
                error_message=None,
                retry_count=0,
                metadata={"domain": {"source": "Example"}},
                created_at="2026-04-27T15:00:00Z",
                updated_at="2026-04-27T15:02:00Z",
                processed_at="2026-04-27T15:03:00Z",
                publication_date="2026-04-25T09:00:00Z",
                is_saved_to_knowledge=True,
                summary="A long-form summary.",
                short_summary="A short summary.",
                summary_kind=SummaryKind.LONG_INTERLEAVED,
                summary_version=SummaryVersion.V2,
                structured_summary={
                    "overview": "A long-form summary.",
                    "bullet_points": [{"text": "First point", "category": "finding"}],
                    "quotes": [{"text": "Important quote", "context": "Interview"}],
                    "topics": ["AI", "Media"],
                },
                bullet_points=[{"text": "First point", "category": "finding"}],
                quotes=[{"text": "Important quote", "context": "Interview"}],
                topics=["AI", "Media"],
                full_markdown="# Long Read\n\nBody",
                body_available=True,
                body_kind="article",
                body_format="markdown",
                image_url="/static/images/content/401.png",
                thumbnail_url="/static/images/thumbnails/401.png",
            ),
            {
                "id": 401,
                "content_type": "article",
                "url": "https://example.com/long-read",
                "source_url": "https://m.example.com/long-read",
                "discussion_url": "https://news.ycombinator.com/item?id=401",
                "title": "Long Read",
                "display_title": "Structured Long Read",
                "source": "Example",
                "status": "completed",
                "error_message": None,
                "retry_count": 0,
                "metadata": {"domain": {"source": "Example"}},
                "created_at": "2026-04-27T15:00:00Z",
                "updated_at": "2026-04-27T15:02:00Z",
                "processed_at": "2026-04-27T15:03:00Z",
                "checked_out_by": None,
                "checked_out_at": None,
                "publication_date": "2026-04-25T09:00:00Z",
                "is_read": False,
                "is_saved_to_knowledge": True,
                "summary": "A long-form summary.",
                "short_summary": "A short summary.",
                "summary_kind": "long_interleaved",
                "summary_version": 2,
                "structured_summary": {
                    "overview": "A long-form summary.",
                    "bullet_points": [{"text": "First point", "category": "finding"}],
                    "quotes": [{"text": "Important quote", "context": "Interview"}],
                    "topics": ["AI", "Media"],
                },
                "bullet_points": [{"text": "First point", "category": "finding"}],
                "quotes": [{"text": "Important quote", "context": "Interview"}],
                "topics": ["AI", "Media"],
                "full_markdown": "# Long Read\n\nBody",
                "body_available": True,
                "body_kind": "article",
                "body_format": "markdown",
                "news_article_url": None,
                "news_discussion_url": None,
                "news_key_points": None,
                "news_summary": None,
                "image_url": "/static/images/content/401.png",
                "thumbnail_url": "/static/images/thumbnails/401.png",
                "detected_feed": None,
                "can_subscribe": False,
            },
        ),
        (
            ContentDetailResponse(
                id=402,
                content_type=ContentType.ARTICLE,
                url="https://newsletter.example.com/p/feed",
                title="Detected Feed",
                display_title="Detected Feed",
                source="Newsletter",
                status=ContentStatus.SKIPPED,
                error_message="Detected feed URL",
                retry_count=1,
                metadata={"processing": {"detected_feed": True}},
                created_at="2026-04-27T16:00:00Z",
                updated_at="2026-04-27T16:01:00Z",
                bullet_points=[],
                quotes=[],
                topics=[],
                detected_feed=DetectedFeed(
                    url="https://newsletter.example.com/feed",
                    type="substack",
                    title="Newsletter",
                    format="rss",
                ),
                can_subscribe=True,
            ),
            {
                "id": 402,
                "content_type": "article",
                "url": "https://newsletter.example.com/p/feed",
                "source_url": None,
                "discussion_url": None,
                "title": "Detected Feed",
                "display_title": "Detected Feed",
                "source": "Newsletter",
                "status": "skipped",
                "error_message": "Detected feed URL",
                "retry_count": 1,
                "metadata": {"processing": {"detected_feed": True}},
                "created_at": "2026-04-27T16:00:00Z",
                "updated_at": "2026-04-27T16:01:00Z",
                "processed_at": None,
                "checked_out_by": None,
                "checked_out_at": None,
                "publication_date": None,
                "is_read": False,
                "is_saved_to_knowledge": False,
                "summary": None,
                "short_summary": None,
                "summary_kind": None,
                "summary_version": None,
                "structured_summary": None,
                "bullet_points": [],
                "quotes": [],
                "topics": [],
                "full_markdown": None,
                "body_available": False,
                "body_kind": None,
                "body_format": None,
                "news_article_url": None,
                "news_discussion_url": None,
                "news_key_points": None,
                "news_summary": None,
                "image_url": None,
                "thumbnail_url": None,
                "detected_feed": {
                    "url": "https://newsletter.example.com/feed",
                    "type": "substack",
                    "title": "Newsletter",
                    "format": "rss",
                },
                "can_subscribe": True,
            },
        ),
        (
            ContentDetailResponse(
                id=403,
                content_type=ContentType.NEWS,
                url="https://news.example.com/items/403",
                title="Failed News Item",
                display_title="Failed News Item",
                source="Mediagazer",
                status=ContentStatus.FAILED,
                error_message="Extraction failed",
                retry_count=3,
                metadata={"processing": {"terminal": True}},
                created_at="2026-04-27T17:00:00Z",
                updated_at="2026-04-27T17:05:00Z",
                bullet_points=[],
                quotes=[],
                topics=[],
                news_article_url="https://publisher.example.com/failed",
                news_discussion_url="https://news.example.com/discuss/403",
                news_key_points=["Known source failed"],
                news_summary="Failure state still preserves typed news fields.",
            ),
            {
                "id": 403,
                "content_type": "news",
                "url": "https://news.example.com/items/403",
                "source_url": None,
                "discussion_url": None,
                "title": "Failed News Item",
                "display_title": "Failed News Item",
                "source": "Mediagazer",
                "status": "failed",
                "error_message": "Extraction failed",
                "retry_count": 3,
                "metadata": {"processing": {"terminal": True}},
                "created_at": "2026-04-27T17:00:00Z",
                "updated_at": "2026-04-27T17:05:00Z",
                "processed_at": None,
                "checked_out_by": None,
                "checked_out_at": None,
                "publication_date": None,
                "is_read": False,
                "is_saved_to_knowledge": False,
                "summary": None,
                "short_summary": None,
                "summary_kind": None,
                "summary_version": None,
                "structured_summary": None,
                "bullet_points": [],
                "quotes": [],
                "topics": [],
                "full_markdown": None,
                "body_available": False,
                "body_kind": None,
                "body_format": None,
                "news_article_url": "https://publisher.example.com/failed",
                "news_discussion_url": "https://news.example.com/discuss/403",
                "news_key_points": ["Known source failed"],
                "news_summary": "Failure state still preserves typed news fields.",
                "image_url": None,
                "thumbnail_url": None,
                "detected_feed": None,
                "can_subscribe": False,
            },
        ),
    ],
)
def test_content_detail_response_contract(
    response: ContentDetailResponse,
    expected: dict[str, object],
) -> None:
    assert _dump(response) == expected
