// Code generated by scripts/generate_go_contracts.py. Do not edit.

package api

import (
	"encoding/json"
	"time"
)

type ContentType string

const (
	ContentTypeArticle ContentType = "article"
	ContentTypePodcast ContentType = "podcast"
	ContentTypeNews ContentType = "news"
	ContentTypeInsightReport ContentType = "insight_report"
	ContentTypeUnknown ContentType = "unknown"
)

func (v ContentType) Known() bool {
	switch v {
	case ContentTypeArticle, ContentTypePodcast, ContentTypeNews, ContentTypeInsightReport, ContentTypeUnknown:
		return true
	default:
		return false
	}
}

type ContentStatus string

const (
	ContentStatusNew ContentStatus = "new"
	ContentStatusPending ContentStatus = "pending"
	ContentStatusProcessing ContentStatus = "processing"
	ContentStatusAwaitingImage ContentStatus = "awaiting_image"
	ContentStatusCompleted ContentStatus = "completed"
	ContentStatusFailed ContentStatus = "failed"
	ContentStatusSkipped ContentStatus = "skipped"
)

func (v ContentStatus) Known() bool {
	switch v {
	case ContentStatusNew, ContentStatusPending, ContentStatusProcessing, ContentStatusAwaitingImage, ContentStatusCompleted, ContentStatusFailed, ContentStatusSkipped:
		return true
	default:
		return false
	}
}

type ContentClassification string

const (
	ContentClassificationToRead ContentClassification = "to_read"
	ContentClassificationSkip ContentClassification = "skip"
)

func (v ContentClassification) Known() bool {
	switch v {
	case ContentClassificationToRead, ContentClassificationSkip:
		return true
	default:
		return false
	}
}

type TaskType string

const (
	TaskTypeScrape TaskType = "scrape"
	TaskTypeBackfillFeeds TaskType = "backfill_feeds"
	TaskTypeAnalyzeURL TaskType = "analyze_url"
	TaskTypeProcessContent TaskType = "process_content"
	TaskTypeEnrichNewsItemArticle TaskType = "enrich_news_item_article"
	TaskTypeProcessNewsItem TaskType = "process_news_item"
	TaskTypeProcessPodcastMedia TaskType = "process_podcast_media"
	TaskTypeDownloadTweetVideoAudio TaskType = "download_tweet_video_audio"
	TaskTypeTranscribeTweetVideo TaskType = "transcribe_tweet_video"
	TaskTypeSummarize TaskType = "summarize"
	TaskTypeFetchDiscussion TaskType = "fetch_discussion"
	TaskTypeFetchNewsItemDiscussion TaskType = "fetch_news_item_discussion"
	TaskTypeGenerateImage TaskType = "generate_image"
	TaskTypeDiscoverFeeds TaskType = "discover_feeds"
	TaskTypeOnboardingDiscover TaskType = "onboarding_discover"
	TaskTypeDigDeeper TaskType = "dig_deeper"
	TaskTypeSyncIntegration TaskType = "sync_integration"
	TaskTypeGenerateAudioEpisode TaskType = "generate_audio_episode"
	TaskTypeRunLLMTask TaskType = "run_llm_task"
	TaskTypeBriefingRefresh TaskType = "briefing_refresh"
	TaskTypeDeleteUserAccount TaskType = "delete_user_account"
)

func (v TaskType) Known() bool {
	switch v {
	case TaskTypeScrape, TaskTypeBackfillFeeds, TaskTypeAnalyzeURL, TaskTypeProcessContent, TaskTypeEnrichNewsItemArticle, TaskTypeProcessNewsItem, TaskTypeProcessPodcastMedia, TaskTypeDownloadTweetVideoAudio, TaskTypeTranscribeTweetVideo, TaskTypeSummarize, TaskTypeFetchDiscussion, TaskTypeFetchNewsItemDiscussion, TaskTypeGenerateImage, TaskTypeDiscoverFeeds, TaskTypeOnboardingDiscover, TaskTypeDigDeeper, TaskTypeSyncIntegration, TaskTypeGenerateAudioEpisode, TaskTypeRunLLMTask, TaskTypeBriefingRefresh, TaskTypeDeleteUserAccount:
		return true
	default:
		return false
	}
}

type TaskStatus string

const (
	TaskStatusPending TaskStatus = "pending"
	TaskStatusProcessing TaskStatus = "processing"
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusFailed TaskStatus = "failed"
)

func (v TaskStatus) Known() bool {
	switch v {
	case TaskStatusPending, TaskStatusProcessing, TaskStatusCompleted, TaskStatusFailed:
		return true
	default:
		return false
	}
}

type SummaryKind string

const (
	SummaryKindLongStructured SummaryKind = "long_structured"
	SummaryKindLongInterleaved SummaryKind = "long_interleaved"
	SummaryKindLongBullets SummaryKind = "long_bullets"
	SummaryKindLongEditorialNarrative SummaryKind = "long_editorial_narrative"
	SummaryKindShortNews SummaryKind = "short_news"
	SummaryKindLongformArtifact SummaryKind = "longform_artifact"
)

func (v SummaryKind) Known() bool {
	switch v {
	case SummaryKindLongStructured, SummaryKindLongInterleaved, SummaryKindLongBullets, SummaryKindLongEditorialNarrative, SummaryKindShortNews, SummaryKindLongformArtifact:
		return true
	default:
		return false
	}
}

type SummaryVersion int

const (
	SummaryVersionV1 SummaryVersion = 1
	SummaryVersionV2 SummaryVersion = 2
)

func (v SummaryVersion) Known() bool {
	switch v {
	case SummaryVersionV1, SummaryVersionV2:
		return true
	default:
		return false
	}
}

type SavedSource string

const (
	SavedSourceKnowledge SavedSource = "knowledge"
	SavedSourceXBookmark SavedSource = "x_bookmark"
)

func (v SavedSource) Known() bool {
	switch v {
	case SavedSourceKnowledge, SavedSourceXBookmark:
		return true
	default:
		return false
	}
}

type OperationStatus string

const (
	OperationStatusSuccess OperationStatus = "success"
)

func (v OperationStatus) Known() bool {
	switch v {
	case OperationStatusSuccess:
		return true
	default:
		return false
	}
}

type SubmissionKind string

const (
	SubmissionKindContent SubmissionKind = "content"
	SubmissionKindFeedSubscription SubmissionKind = "feed_subscription"
	SubmissionKindLearningDeck SubmissionKind = "learning_deck"
)

func (v SubmissionKind) Known() bool {
	switch v {
	case SubmissionKindContent, SubmissionKindFeedSubscription, SubmissionKindLearningDeck:
		return true
	default:
		return false
	}
}

type SubmissionOutcome string

const (
	SubmissionOutcomeQueued SubmissionOutcome = "queued"
	SubmissionOutcomeProcessing SubmissionOutcome = "processing"
	SubmissionOutcomeCompleted SubmissionOutcome = "completed"
	SubmissionOutcomeFailed SubmissionOutcome = "failed"
	SubmissionOutcomeSkipped SubmissionOutcome = "skipped"
	SubmissionOutcomeSubscribed SubmissionOutcome = "subscribed"
	SubmissionOutcomeAlreadySubscribed SubmissionOutcome = "already_subscribed"
	SubmissionOutcomeFeedNotFound SubmissionOutcome = "feed_not_found"
	SubmissionOutcomeFeedFetchFailed SubmissionOutcome = "feed_fetch_failed"
	SubmissionOutcomeFeedSubscriptionFailed SubmissionOutcome = "feed_subscription_failed"
)

func (v SubmissionOutcome) Known() bool {
	switch v {
	case SubmissionOutcomeQueued, SubmissionOutcomeProcessing, SubmissionOutcomeCompleted, SubmissionOutcomeFailed, SubmissionOutcomeSkipped, SubmissionOutcomeSubscribed, SubmissionOutcomeAlreadySubscribed, SubmissionOutcomeFeedNotFound, SubmissionOutcomeFeedFetchFailed, SubmissionOutcomeFeedSubscriptionFailed:
		return true
	default:
		return false
	}
}

type BriefingTier string

const (
	BriefingTierAudio BriefingTier = "audio"
	BriefingTierLongform BriefingTier = "longform"
	BriefingTierNews BriefingTier = "news"
)

func (v BriefingTier) Known() bool {
	switch v {
	case BriefingTierAudio, BriefingTierLongform, BriefingTierNews:
		return true
	default:
		return false
	}
}

type BriefingFirstRunPhase string

const (
	BriefingFirstRunPhaseActive BriefingFirstRunPhase = "active"
	BriefingFirstRunPhaseReady BriefingFirstRunPhase = "ready"
	BriefingFirstRunPhaseWaitingForContent BriefingFirstRunPhase = "waiting_for_content"
)

func (v BriefingFirstRunPhase) Known() bool {
	switch v {
	case BriefingFirstRunPhaseActive, BriefingFirstRunPhaseReady, BriefingFirstRunPhaseWaitingForContent:
		return true
	default:
		return false
	}
}

type BriefingFirstRunSourceOutcome string

const (
	BriefingFirstRunSourceOutcomeProcessed BriefingFirstRunSourceOutcome = "processed"
	BriefingFirstRunSourceOutcomeUnavailable BriefingFirstRunSourceOutcome = "unavailable"
)

func (v BriefingFirstRunSourceOutcome) Known() bool {
	switch v {
	case BriefingFirstRunSourceOutcomeProcessed, BriefingFirstRunSourceOutcomeUnavailable:
		return true
	default:
		return false
	}
}

type ReadingExperience string

const (
	ReadingExperienceClassic ReadingExperience = "classic"
	ReadingExperienceBriefing ReadingExperience = "briefing"
)

func (v ReadingExperience) Known() bool {
	switch v {
	case ReadingExperienceClassic, ReadingExperienceBriefing:
		return true
	default:
		return false
	}
}

type BriefingBlockType string

const (
	BriefingBlockTypePassage BriefingBlockType = "passage"
	BriefingBlockTypeFigure BriefingBlockType = "figure"
	BriefingBlockTypePullquote BriefingBlockType = "pullquote"
)

func (v BriefingBlockType) Known() bool {
	switch v {
	case BriefingBlockTypePassage, BriefingBlockTypeFigure, BriefingBlockTypePullquote:
		return true
	default:
		return false
	}
}

type BriefingFigureAlignment string

const (
	BriefingFigureAlignmentLeft BriefingFigureAlignment = "left"
	BriefingFigureAlignmentRight BriefingFigureAlignment = "right"
)

func (v BriefingFigureAlignment) Known() bool {
	switch v {
	case BriefingFigureAlignmentLeft, BriefingFigureAlignmentRight:
		return true
	default:
		return false
	}
}

type BriefingFigurePlacement string

const (
	BriefingFigurePlacementInset BriefingFigurePlacement = "inset"
	BriefingFigurePlacementFull BriefingFigurePlacement = "full"
)

func (v BriefingFigurePlacement) Known() bool {
	switch v {
	case BriefingFigurePlacementInset, BriefingFigurePlacementFull:
		return true
	default:
		return false
	}
}

type BriefingRunKind string

const (
	BriefingRunKindText BriefingRunKind = "text"
	BriefingRunKindSourceLink BriefingRunKind = "source_link"
	BriefingRunKindInsight BriefingRunKind = "insight"
)

func (v BriefingRunKind) Known() bool {
	switch v {
	case BriefingRunKindText, BriefingRunKindSourceLink, BriefingRunKindInsight:
		return true
	default:
		return false
	}
}

type CliLinkStatus string

const (
	CliLinkStatusPending CliLinkStatus = "pending"
	CliLinkStatusApproved CliLinkStatus = "approved"
	CliLinkStatusClaimed CliLinkStatus = "claimed"
	CliLinkStatusExpired CliLinkStatus = "expired"
)

func (v CliLinkStatus) Known() bool {
	switch v {
	case CliLinkStatusPending, CliLinkStatusApproved, CliLinkStatusClaimed, CliLinkStatusExpired:
		return true
	default:
		return false
	}
}

type AgentLibraryDocumentVariant string

const (
	AgentLibraryDocumentVariantSource AgentLibraryDocumentVariant = "source"
	AgentLibraryDocumentVariantSummary AgentLibraryDocumentVariant = "summary"
)

func (v AgentLibraryDocumentVariant) Known() bool {
	switch v {
	case AgentLibraryDocumentVariantSource, AgentLibraryDocumentVariantSummary:
		return true
	default:
		return false
	}
}

type AgentSearchResultKind string

const (
	AgentSearchResultKindWeb AgentSearchResultKind = "web"
	AgentSearchResultKindPodcast AgentSearchResultKind = "podcast"
)

func (v AgentSearchResultKind) Known() bool {
	switch v {
	case AgentSearchResultKindWeb, AgentSearchResultKindPodcast:
		return true
	default:
		return false
	}
}

type OnboardingSuggestionType string

const (
	OnboardingSuggestionTypeSubstack OnboardingSuggestionType = "substack"
	OnboardingSuggestionTypeAtom OnboardingSuggestionType = "atom"
	OnboardingSuggestionTypePodcastRSS OnboardingSuggestionType = "podcast_rss"
	OnboardingSuggestionTypeReddit OnboardingSuggestionType = "reddit"
)

func (v OnboardingSuggestionType) Known() bool {
	switch v {
	case OnboardingSuggestionTypeSubstack, OnboardingSuggestionTypeAtom, OnboardingSuggestionTypePodcastRSS, OnboardingSuggestionTypeReddit:
		return true
	default:
		return false
	}
}

type ContentListResponse struct {
	Contents []ContentSummaryResponse `json:"contents"`
	AvailableDates []string `json:"available_dates"`
	ContentTypes []ContentType `json:"content_types"`
	Meta PaginationMetadata `json:"meta"`
}

type ContentDetailResponse struct {
	ID int `json:"id"`
	ContentType ContentType `json:"content_type"`
	URL string `json:"url"`
	SourceURL *string `json:"source_url,omitempty"`
	DiscussionURL *string `json:"discussion_url,omitempty"`
	Title *string `json:"title,omitempty"`
	DisplayTitle string `json:"display_title"`
	Source *string `json:"source,omitempty"`
	Status ContentStatus `json:"status"`
	ErrorMessage *string `json:"error_message,omitempty"`
	RetryCount int `json:"retry_count"`
	Metadata json.RawMessage `json:"metadata"`
	CreatedAt string `json:"created_at"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	ProcessedAt *string `json:"processed_at,omitempty"`
	CheckedOutBy *string `json:"checked_out_by,omitempty"`
	CheckedOutAt *string `json:"checked_out_at,omitempty"`
	PublicationDate *string `json:"publication_date,omitempty"`
	IsRead *bool `json:"is_read,omitempty"`
	IsSavedToKnowledge *bool `json:"is_saved_to_knowledge,omitempty"`
	Summary *string `json:"summary,omitempty"`
	ShortSummary *string `json:"short_summary,omitempty"`
	SummaryKind *SummaryKind `json:"summary_kind,omitempty"`
	SummaryVersion *SummaryVersion `json:"summary_version,omitempty"`
	StructuredSummary json.RawMessage `json:"structured_summary,omitempty"`
	LongformArtifact json.RawMessage `json:"longform_artifact,omitempty"`
	FeedPreview json.RawMessage `json:"feed_preview,omitempty"`
	ArtifactType *string `json:"artifact_type,omitempty"`
	PreviewBullets []string `json:"preview_bullets,omitempty"`
	ReasonToRead *string `json:"reason_to_read,omitempty"`
	BulletPoints []ContentSummaryBulletPoint `json:"bullet_points,omitempty"`
	Quotes []ContentSummaryQuote `json:"quotes,omitempty"`
	Topics []string `json:"topics,omitempty"`
	FullMarkdown *string `json:"full_markdown,omitempty"`
	BodyAvailable *bool `json:"body_available,omitempty"`
	BodyKind *string `json:"body_kind,omitempty"`
	BodyFormat *string `json:"body_format,omitempty"`
	NewsArticleURL *string `json:"news_article_url,omitempty"`
	NewsDiscussionURL *string `json:"news_discussion_url,omitempty"`
	NewsKeyPoints []string `json:"news_key_points,omitempty"`
	NewsSummary *string `json:"news_summary,omitempty"`
	ImageURL *string `json:"image_url,omitempty"`
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`
	DetectedFeed *DetectedFeed `json:"detected_feed,omitempty"`
	CanSubscribe *bool `json:"can_subscribe,omitempty"`
}

type SubmissionStatusListResponse struct {
	Submissions []SubmissionStatusResponse `json:"submissions"`
	Meta PaginationMetadata `json:"meta"`
}

type BulkMarkReadRequest struct {
	ContentIDs []int `json:"content_ids"`
}

type BulkMarkReadResponse struct {
	Status *OperationStatus `json:"status,omitempty"`
	MarkedCount int `json:"marked_count"`
	FailedIDs []int `json:"failed_ids,omitempty"`
	TotalRequested int `json:"total_requested"`
}

type JobStatusResponse struct {
	ID int `json:"id"`
	TaskType string `json:"task_type"`
	Status string `json:"status"`
	QueueName string `json:"queue_name"`
	ContentID *int `json:"content_id,omitempty"`
	Payload json.RawMessage `json:"payload,omitempty"`
	RetryCount *int `json:"retry_count,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	StartedAt *time.Time `json:"started_at,omitempty"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	ErrorMessage *string `json:"error_message,omitempty"`
}

type BriefingIndexResponse struct {
	Version int `json:"version"`
	MastheadTitle string `json:"masthead_title"`
	MastheadDeck string `json:"masthead_deck"`
	GeneratedAt *time.Time `json:"generated_at,omitempty"`
	Lenses []BriefingLensSummary `json:"lenses,omitempty"`
	FirstRun *BriefingFirstRunProgress `json:"first_run,omitempty"`
}

type BriefingFirstRunProgress struct {
	RunID int `json:"run_id"`
	Revision int `json:"revision"`
	Phase BriefingFirstRunPhase `json:"phase"`
	ConnectedSourceCount int `json:"connected_source_count"`
	CompletedSources []BriefingFirstRunSourceProgress `json:"completed_sources,omitempty"`
	ActiveSources []string `json:"active_sources,omitempty"`
	QueuedSources []string `json:"queued_sources,omitempty"`
	ReadyCategoryKeys []string `json:"ready_category_keys,omitempty"`
}

type BriefingLensSummary struct {
	Key string `json:"key"`
	Tier BriefingTier `json:"tier"`
	Title string `json:"title"`
	Deck string `json:"deck"`
	Position int `json:"position"`
	SegmentCount int `json:"segment_count"`
	UnreadSourceCount int `json:"unread_source_count"`
}

type BriefingLensResponse struct {
	Version int `json:"version"`
	Lens BriefingLensSummary `json:"lens"`
	Segments []BriefingSegment `json:"segments,omitempty"`
	Sources []BriefingSource `json:"sources,omitempty"`
	NextCursor *string `json:"next_cursor,omitempty"`
	HasMore *bool `json:"has_more,omitempty"`
}

type BriefingSegment struct {
	ID int `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	Status string `json:"status"`
	NarrationText string `json:"narration_text"`
	Blocks []BriefingBlock `json:"blocks,omitempty"`
	SourceKeys []string `json:"source_keys,omitempty"`
}

type BriefingDiscussion struct {
	Platform string `json:"platform"`
	CommentCount *int `json:"comment_count,omitempty"`
	SummaryStatus string `json:"summary_status"`
	Overview *string `json:"overview,omitempty"`
	TopCommentAuthor *string `json:"top_comment_author,omitempty"`
	TopCommentText *string `json:"top_comment_text,omitempty"`
	ExternalURL *string `json:"external_url,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

type BriefingSource struct {
	SourceKey string `json:"source_key"`
	Kind string `json:"kind"`
	ID int `json:"id"`
	Title string `json:"title"`
	Summary *string `json:"summary,omitempty"`
	KeyPoints []string `json:"key_points,omitempty"`
	URL *string `json:"url,omitempty"`
	ImageURL *string `json:"image_url,omitempty"`
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`
	PublishedAt *time.Time `json:"published_at,omitempty"`
	ContentType *ContentType `json:"content_type,omitempty"`
	Read *bool `json:"read,omitempty"`
	Discussion *BriefingDiscussion `json:"discussion,omitempty"`
}

type BriefingReadMarkRequest struct {
	SourceKeys []string `json:"source_keys"`
}

type BriefingReadMarkResponse struct {
	Marked int `json:"marked"`
	Retired int `json:"retired"`
	Version int `json:"version"`
}

type BriefingRefreshResponse struct {
	Enqueued bool `json:"enqueued"`
	Version int `json:"version"`
}

type ScraperConfigResponse struct {
	ID int `json:"id"`
	ScraperType string `json:"scraper_type"`
	DisplayName *string `json:"display_name,omitempty"`
	Config json.RawMessage `json:"config"`
	FeedURL *string `json:"feed_url,omitempty"`
	Limit *int `json:"limit,omitempty"`
	IsActive bool `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	Stats *ScraperConfigStatsResponse `json:"stats,omitempty"`
}

type SubscribeToFeedRequest struct {
	FeedURL string `json:"feed_url"`
	FeedType string `json:"feed_type"`
	DisplayName *string `json:"display_name,omitempty"`
}

type OnboardingDiscoveryStatusResponse struct {
	RunID int `json:"run_id"`
	RunStatus string `json:"run_status"`
	TopicSummary *string `json:"topic_summary,omitempty"`
	InferredTopics []string `json:"inferred_topics,omitempty"`
	Lanes []OnboardingDiscoveryLaneStatus `json:"lanes,omitempty"`
	Suggestions *OnboardingFastDiscoverResponse `json:"suggestions,omitempty"`
	ErrorMessage *string `json:"error_message,omitempty"`
}

type OnboardingCompleteResponse struct {
	Status string `json:"status"`
	TaskID *int `json:"task_id,omitempty"`
	InboxCountEstimate int `json:"inbox_count_estimate"`
	ConfiguredSourceCount int `json:"configured_source_count"`
	LongformStatus string `json:"longform_status"`
	HasCompletedOnboarding bool `json:"has_completed_onboarding"`
	HasCompletedNewUserTutorial bool `json:"has_completed_new_user_tutorial"`
}

type AgentSearchRequest struct {
	Query string `json:"query"`
	Limit *int `json:"limit,omitempty"`
	IncludePodcasts *bool `json:"include_podcasts,omitempty"`
}

type AgentSearchResponse struct {
	Results []AgentSearchResultResponse `json:"results,omitempty"`
}

type AgentOnboardingStartRequest struct {
	Brief string `json:"brief"`
	Preferences json.RawMessage `json:"preferences,omitempty"`
	SeedURLs []string `json:"seed_urls,omitempty"`
	SeedFeeds []string `json:"seed_feeds,omitempty"`
}

type AgentOnboardingStartResponse struct {
	RunID int `json:"run_id"`
	Status string `json:"status"`
	JobID *int `json:"job_id,omitempty"`
}

type AgentOnboardingCompleteRequest struct {
	AcceptAll *bool `json:"accept_all,omitempty"`
	SourceIDs []int `json:"source_ids,omitempty"`
	SelectedSubreddits []string `json:"selected_subreddits,omitempty"`
	SelectedAggregators []OnboardingSelectedAggregator `json:"selected_aggregators,omitempty"`
}

type CliLinkStartRequest struct {
	DeviceName *string `json:"device_name,omitempty"`
}

type CliLinkStartResponse struct {
	SessionID string `json:"session_id"`
	Status CliLinkStatus `json:"status"`
	PollToken string `json:"poll_token"`
	ApproveURL string `json:"approve_url"`
	ExpiresAt time.Time `json:"expires_at"`
	PollIntervalSeconds *int `json:"poll_interval_seconds,omitempty"`
}

type CliLinkApproveRequest struct {
	ApproveToken string `json:"approve_token"`
	DeviceName *string `json:"device_name,omitempty"`
}

type CliLinkApproveResponse struct {
	SessionID string `json:"session_id"`
	Status CliLinkStatus `json:"status"`
	KeyPrefix string `json:"key_prefix"`
	ExpiresAt time.Time `json:"expires_at"`
}

type CliLinkPollResponse struct {
	SessionID string `json:"session_id"`
	Status CliLinkStatus `json:"status"`
	ExpiresAt time.Time `json:"expires_at"`
	APIKey *string `json:"api_key,omitempty"`
	KeyPrefix *string `json:"key_prefix,omitempty"`
}

type AgentLibraryManifestResponse struct {
	GeneratedAt time.Time `json:"generated_at"`
	IncludeSource *bool `json:"include_source,omitempty"`
	Documents []AgentLibraryDocumentResponse `json:"documents"`
}

type AgentLibraryFileResponse struct {
	RelativePath string `json:"relative_path"`
	ContentID int `json:"content_id"`
	Variant AgentLibraryDocumentVariant `json:"variant"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	ChecksumSHA256 string `json:"checksum_sha256"`
	Text string `json:"text"`
}

type SubmitContentRequest struct {
	URL string `json:"url"`
	ContentType *ContentType `json:"content_type,omitempty"`
	Title *string `json:"title,omitempty"`
	Platform *string `json:"platform,omitempty"`
	Instruction *string `json:"instruction,omitempty"`
	CrawlLinks *bool `json:"crawl_links,omitempty"`
	SubscribeToFeed *bool `json:"subscribe_to_feed,omitempty"`
	ShareAndChat *bool `json:"share_and_chat,omitempty"`
	ChatInitialMessage *string `json:"chat_initial_message,omitempty"`
	SaveToKnowledgeAndMarkRead *bool `json:"save_to_knowledge_and_mark_read,omitempty"`
}

type ContentSubmissionResponse struct {
	ContentID int `json:"content_id"`
	ContentType ContentType `json:"content_type"`
	Status ContentStatus `json:"status"`
	Platform *string `json:"platform,omitempty"`
	AlreadyExists *bool `json:"already_exists,omitempty"`
	Message string `json:"message"`
	TaskID *int `json:"task_id,omitempty"`
	Source *string `json:"source,omitempty"`
}

type ConvertNewsItemResponse struct {
	Status *string `json:"status,omitempty"`
	NewsItemID int `json:"news_item_id"`
	NewContentID int `json:"new_content_id"`
	AlreadyExists bool `json:"already_exists"`
	Message string `json:"message"`
}

type ContentSummaryResponse struct {
	ID int `json:"id"`
	ContentType ContentType `json:"content_type"`
	URL string `json:"url"`
	SourceURL *string `json:"source_url,omitempty"`
	DiscussionURL *string `json:"discussion_url,omitempty"`
	Title *string `json:"title,omitempty"`
	Source *string `json:"source,omitempty"`
	Platform *string `json:"platform,omitempty"`
	Status ContentStatus `json:"status"`
	ShortSummary *string `json:"short_summary,omitempty"`
	CreatedAt string `json:"created_at"`
	ProcessedAt *string `json:"processed_at,omitempty"`
	Classification *ContentClassification `json:"classification,omitempty"`
	PublicationDate *string `json:"publication_date,omitempty"`
	IsRead *bool `json:"is_read,omitempty"`
	IsSavedToKnowledge *bool `json:"is_saved_to_knowledge,omitempty"`
	NewsArticleURL *string `json:"news_article_url,omitempty"`
	NewsDiscussionURL *string `json:"news_discussion_url,omitempty"`
	NewsKeyPoints []string `json:"news_key_points,omitempty"`
	NewsSummary *string `json:"news_summary,omitempty"`
	UserStatus *string `json:"user_status,omitempty"`
	ImageURL *string `json:"image_url,omitempty"`
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`
	PrimaryTopic *string `json:"primary_topic,omitempty"`
	TopComment map[string]string `json:"top_comment,omitempty"`
	CommentCount *int `json:"comment_count,omitempty"`
	FeedPreview json.RawMessage `json:"feed_preview,omitempty"`
	ArtifactType *string `json:"artifact_type,omitempty"`
	PreviewBullets []string `json:"preview_bullets,omitempty"`
	ReasonToRead *string `json:"reason_to_read,omitempty"`
	KeyTakeaway *string `json:"key_takeaway,omitempty"`
	SavedSource *SavedSource `json:"saved_source,omitempty"`
}

type PaginationMetadata struct {
	NextCursor *string `json:"next_cursor,omitempty"`
	HasMore *bool `json:"has_more,omitempty"`
	PageSize int `json:"page_size"`
	Total *int `json:"total,omitempty"`
}

type ContentSummaryBulletPoint struct {
	Text string `json:"text"`
	Category *string `json:"category,omitempty"`
}

type ContentSummaryQuote struct {
	Text string `json:"text"`
	Context *string `json:"context,omitempty"`
	Attribution *string `json:"attribution,omitempty"`
}

type DetectedFeed struct {
	URL string `json:"url"`
	Type string `json:"type"`
	Title *string `json:"title,omitempty"`
	Format *string `json:"format,omitempty"`
}

type SubmissionStatusResponse struct {
	ID int `json:"id"`
	ContentType ContentType `json:"content_type"`
	URL string `json:"url"`
	SourceURL *string `json:"source_url,omitempty"`
	Title *string `json:"title,omitempty"`
	Status ContentStatus `json:"status"`
	ErrorMessage *string `json:"error_message,omitempty"`
	CreatedAt string `json:"created_at"`
	ProcessedAt *string `json:"processed_at,omitempty"`
	SubmittedVia *string `json:"submitted_via,omitempty"`
	IsSelfSubmission *bool `json:"is_self_submission,omitempty"`
	SubmissionKind *SubmissionKind `json:"submission_kind,omitempty"`
	Outcome *SubmissionOutcome `json:"outcome,omitempty"`
	DetectedFeed *DetectedFeed `json:"detected_feed,omitempty"`
	FeedSubscription *SubmissionFeedSubscriptionResponse `json:"feed_subscription,omitempty"`
}

type BriefingFirstRunSourceProgress struct {
	DisplayName string `json:"display_name"`
	ProcessedItemCount int `json:"processed_item_count"`
	Outcome BriefingFirstRunSourceOutcome `json:"outcome"`
}

type BriefingBlock struct {
	Type BriefingBlockType `json:"type"`
	Weight *string `json:"weight,omitempty"`
	Paragraphs []BriefingParagraph `json:"paragraphs,omitempty"`
	SourceKey *string `json:"source_key,omitempty"`
	ImageURL *string `json:"image_url,omitempty"`
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`
	Caption *string `json:"caption,omitempty"`
	Placement *BriefingFigurePlacement `json:"placement,omitempty"`
	Alignment *BriefingFigureAlignment `json:"alignment,omitempty"`
	Text *string `json:"text,omitempty"`
}

type ScraperConfigStatsResponse struct {
	TotalCount int `json:"total_count"`
	CompletedCount int `json:"completed_count"`
	UnreadCount int `json:"unread_count"`
	ProcessingCount int `json:"processing_count"`
	LatestProcessedAt *time.Time `json:"latest_processed_at,omitempty"`
	LatestPublicationAt *time.Time `json:"latest_publication_at,omitempty"`
	NextExpectedAt *time.Time `json:"next_expected_at,omitempty"`
	AverageIntervalHours *float64 `json:"average_interval_hours,omitempty"`
	IntervalSampleSize *int `json:"interval_sample_size,omitempty"`
}

type OnboardingDiscoveryLaneStatus struct {
	Name string `json:"name"`
	Status string `json:"status"`
	CompletedQueries *int `json:"completed_queries,omitempty"`
	QueryCount *int `json:"query_count,omitempty"`
}

type OnboardingFastDiscoverResponse struct {
	RecommendedPods []OnboardingSuggestion `json:"recommended_pods,omitempty"`
	RecommendedSubstacks []OnboardingSuggestion `json:"recommended_substacks,omitempty"`
	RecommendedSubreddits []OnboardingSuggestion `json:"recommended_subreddits,omitempty"`
}

type OnboardingSelectedAggregator struct {
	Key string `json:"key"`
	Title *string `json:"title,omitempty"`
	Topics []string `json:"topics,omitempty"`
}

type AgentSearchResultResponse struct {
	Kind AgentSearchResultKind `json:"kind"`
	Title string `json:"title"`
	URL string `json:"url"`
	Snippet *string `json:"snippet,omitempty"`
	Source *string `json:"source,omitempty"`
	Provider *string `json:"provider,omitempty"`
	FeedURL *string `json:"feed_url,omitempty"`
	PublishedAt *string `json:"published_at,omitempty"`
	Score *float64 `json:"score,omitempty"`
}

type AgentLibraryDocumentResponse struct {
	RelativePath string `json:"relative_path"`
	ContentID int `json:"content_id"`
	Variant AgentLibraryDocumentVariant `json:"variant"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	SizeBytes int `json:"size_bytes"`
	ChecksumSHA256 string `json:"checksum_sha256"`
}

type SubmissionFeedSubscriptionResponse struct {
	Status string `json:"status"`
	FeedURL *string `json:"feed_url,omitempty"`
	FeedType *string `json:"feed_type,omitempty"`
	Created *bool `json:"created,omitempty"`
	ConfigID *int `json:"config_id,omitempty"`
	InitialDownload *SubmissionFeedInitialDownloadResponse `json:"initial_download,omitempty"`
}

type BriefingParagraph struct {
	Runs []BriefingRun `json:"runs,omitempty"`
}

type OnboardingSuggestion struct {
	SuggestionType OnboardingSuggestionType `json:"suggestion_type"`
	Title *string `json:"title,omitempty"`
	SiteURL *string `json:"site_url,omitempty"`
	FeedURL *string `json:"feed_url,omitempty"`
	Subreddit *string `json:"subreddit,omitempty"`
	Rationale *string `json:"rationale,omitempty"`
	Score *float64 `json:"score,omitempty"`
	IsDefault *bool `json:"is_default,omitempty"`
}

type SubmissionFeedInitialDownloadResponse struct {
	RequestedCount *int `json:"requested_count,omitempty"`
	Ran *bool `json:"ran,omitempty"`
	Status *string `json:"status,omitempty"`
	Reason *string `json:"reason,omitempty"`
	Error *string `json:"error,omitempty"`
	ConfigID *int `json:"config_id,omitempty"`
	BaseLimit *int `json:"base_limit,omitempty"`
	TargetLimit *int `json:"target_limit,omitempty"`
	Scraped *int `json:"scraped,omitempty"`
	Saved *int `json:"saved,omitempty"`
	Duplicates *int `json:"duplicates,omitempty"`
	Errors *int `json:"errors,omitempty"`
}

type BriefingRun struct {
	Kind BriefingRunKind `json:"kind"`
	Text string `json:"text"`
	SourceKey *string `json:"source_key,omitempty"`
	InsightID *string `json:"insight_id,omitempty"`
	Bold *bool `json:"bold,omitempty"`
}
