// Code generated by ogen, DO NOT EDIT.
package api

type ApproveCliLinkRes interface {
	approveCliLinkRes()
}

type CompleteOnboardingRes interface {
	completeOnboardingRes()
}

type ConvertNewsItemToArticleRes interface {
	convertNewsItemToArticleRes()
}

type GetAgentLibraryFileRes interface {
	getAgentLibraryFileRes()
}

type GetAgentLibraryManifestRes interface {
	getAgentLibraryManifestRes()
}

type GetContentDetailRes interface {
	getContentDetailRes()
}

type GetJobRes interface {
	getJobRes()
}

type GetNewsItemRes interface {
	getNewsItemRes()
}

type GetOnboardingRes interface {
	getOnboardingRes()
}

type ListContentSubmissionStatusesRes interface {
	listContentSubmissionStatusesRes()
}

type ListContentsRes interface {
	listContentsRes()
}

type ListNewsItemsRes interface {
	listNewsItemsRes()
}

type ListScraperConfigsRes interface {
	listScraperConfigsRes()
}

type MarkNewsItemsReadRes interface {
	markNewsItemsReadRes()
}

type PollCliLinkRes interface {
	pollCliLinkRes()
}

type SearchAgentRes interface {
	searchAgentRes()
}

type StartCliLinkRes interface {
	startCliLinkRes()
}

type StartOnboardingRes interface {
	startOnboardingRes()
}

type SubmitContentRes interface {
	submitContentRes()
}

type SubscribeScrapersToFeedRes interface {
	subscribeScrapersToFeedRes()
}
