// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleHTTPBearer handles HTTPBearer security.
	HandleHTTPBearer(ctx context.Context, operationName OperationName, t HTTPBearer) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesHTTPBearer is a private map storing roles per operation.
var operationRolesHTTPBearer = map[string][]string{
	CompleteOnboardingOperation: []string{},
	GenerateDigestOperation:     []string{},
	GetContentOperation:         []string{},
	GetJobOperation:             []string{},
	GetOnboardingOperation:      []string{},
	ListContentOperation:        []string{},
	ListDigestsOperation:        []string{},
	ListSourcesOperation:        []string{},
	SearchAgentOperation:        []string{},
	StartOnboardingOperation:    []string{},
	SubmitContentOperation:      []string{},
	SubscribeSourceOperation:    []string{},
}

// GetRolesForHTTPBearer returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForHTTPBearer(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForHTTPBearer(operation string) []string {
	roles, ok := operationRolesHTTPBearer[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityHTTPBearer(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t HTTPBearer
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesHTTPBearer[operationName]
	rctx, err := s.sec.HandleHTTPBearer(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// HTTPBearer provides HTTPBearer security value.
	HTTPBearer(ctx context.Context, operationName OperationName) (HTTPBearer, error)
}

func (s *Client) securityHTTPBearer(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.HTTPBearer(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"HTTPBearer\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
