// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ApproveCliLink implements approveCliLink operation.
	//
	// Approve one pending CLI link session from the authenticated app.
	//
	// POST /api/agent/cli/link/{session_id}/approve
	ApproveCliLink(ctx context.Context, req *CliLinkApproveRequest, params ApproveCliLinkParams) (ApproveCliLinkRes, error)
	// CompleteOnboarding implements completeOnboarding operation.
	//
	// Complete onboarding from simplified selections.
	//
	// POST /api/agent/onboarding/{run_id}/complete
	CompleteOnboarding(ctx context.Context, req *AgentOnboardingCompleteRequest, params CompleteOnboardingParams) (CompleteOnboardingRes, error)
	// ConvertNewsItemToArticle implements convertNewsItemToArticle operation.
	//
	// Convert one representative news item into saved article content.
	//
	// POST /api/news/items/{news_item_id}/convert-to-article
	ConvertNewsItemToArticle(ctx context.Context, params ConvertNewsItemToArticleParams) (ConvertNewsItemToArticleRes, error)
	// GetAgentLibraryFile implements getAgentLibraryFile operation.
	//
	// Return one rendered markdown document by relative manifest path.
	//
	// GET /api/agent/library/file
	GetAgentLibraryFile(ctx context.Context, params GetAgentLibraryFileParams) (GetAgentLibraryFileRes, error)
	// GetAgentLibraryManifest implements getAgentLibraryManifest operation.
	//
	// Return manifest metadata for exportable per-user markdown files.
	//
	// GET /api/agent/library/manifest
	GetAgentLibraryManifest(ctx context.Context, params GetAgentLibraryManifestParams) (GetAgentLibraryManifestRes, error)
	// GetContentDetail implements getContentDetail operation.
	//
	// Retrieve detailed information about a specific content item.
	//
	// GET /api/content/{content_id}
	GetContentDetail(ctx context.Context, params GetContentDetailParams) (GetContentDetailRes, error)
	// GetJob implements getJob operation.
	//
	// Return async job status.
	//
	// GET /api/jobs/{job_id}
	GetJob(ctx context.Context, params GetJobParams) (GetJobRes, error)
	// GetNewsItem implements getNewsItem operation.
	//
	// Return one visible representative news item.
	//
	// GET /api/news/items/{news_item_id}
	GetNewsItem(ctx context.Context, params GetNewsItemParams) (GetNewsItemRes, error)
	// GetOnboarding implements getOnboarding operation.
	//
	// Return onboarding run status.
	//
	// GET /api/agent/onboarding/{run_id}
	GetOnboarding(ctx context.Context, params GetOnboardingParams) (GetOnboardingRes, error)
	// ListContentSubmissionStatuses implements listContentSubmissionStatuses operation.
	//
	// Returns self-submitted content items that are not yet completed, including processing, failed, and
	// skipped statuses.
	//
	// GET /api/content/submissions/list
	ListContentSubmissionStatuses(ctx context.Context, params ListContentSubmissionStatusesParams) (ListContentSubmissionStatusesRes, error)
	// ListContents implements listContents operation.
	//
	// Retrieve a list of content items with optional filtering by content type and date. Supports
	// multiple content types via repeated query parameters (e.g.,
	// ?content_type=article&content_type=podcast). Supports cursor-based pagination for efficient
	// loading.
	//
	// GET /api/content/
	ListContents(ctx context.Context, params ListContentsParams) (ListContentsRes, error)
	// ListNewsItems implements listNewsItems operation.
	//
	// Return the visible representative news feed for the current user.
	//
	// GET /api/news/items
	ListNewsItems(ctx context.Context, params ListNewsItemsParams) (ListNewsItemsRes, error)
	// ListScraperConfigs implements listScraperConfigs operation.
	//
	// List scraper configurations for the current user.
	//
	// GET /api/scrapers/
	ListScraperConfigs(ctx context.Context, params ListScraperConfigsParams) (ListScraperConfigsRes, error)
	// MarkNewsItemsRead implements markNewsItemsRead operation.
	//
	// Mark the given visible representative news items as read.
	//
	// POST /api/news/items/mark-read
	MarkNewsItemsRead(ctx context.Context, req *BulkMarkReadRequest) (MarkNewsItemsReadRes, error)
	// PollCliLink implements pollCliLink operation.
	//
	// Poll a pending CLI link session without requiring existing auth.
	//
	// GET /api/agent/cli/link/{session_id}
	PollCliLink(ctx context.Context, params PollCliLinkParams) (PollCliLinkRes, error)
	// SearchAgent implements searchAgent operation.
	//
	// Search external/provider-backed sources for the agent CLI.
	//
	// POST /api/agent/search
	SearchAgent(ctx context.Context, req *AgentSearchRequest) (SearchAgentRes, error)
	// StartCliLink implements startCliLink operation.
	//
	// Create an unauthenticated QR approval session for the CLI.
	//
	// POST /api/agent/cli/link/start
	StartCliLink(ctx context.Context, req OptCliLinkStartRequest) (StartCliLinkRes, error)
	// StartOnboarding implements startOnboarding operation.
	//
	// Start simplified async onboarding.
	//
	// POST /api/agent/onboarding
	StartOnboarding(ctx context.Context, req *AgentOnboardingStartRequest) (StartOnboardingRes, error)
	// SubmitContent implements submitContent operation.
	//
	// Submit article or podcast URLs for processing. Only http/https URLs are accepted.
	//
	// POST /api/content/submit
	SubmitContent(ctx context.Context, req *SubmitContentRequest) (SubmitContentRes, error)
	// SubscribeScrapersToFeed implements subscribeScrapersToFeed operation.
	//
	// Subscribe to a feed detected from content.
	// Convenience endpoint that creates a scraper config from a detected feed.
	//
	// POST /api/scrapers/subscribe
	SubscribeScrapersToFeed(ctx context.Context, req *SubscribeToFeedRequest) (SubscribeScrapersToFeedRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
