// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CompleteOnboardingOperation OperationName = "CompleteOnboarding"
	GenerateDigestOperation     OperationName = "GenerateDigest"
	GetContentOperation         OperationName = "GetContent"
	GetJobOperation             OperationName = "GetJob"
	GetOnboardingOperation      OperationName = "GetOnboarding"
	ListContentOperation        OperationName = "ListContent"
	ListDigestsOperation        OperationName = "ListDigests"
	ListSourcesOperation        OperationName = "ListSources"
	SearchAgentOperation        OperationName = "SearchAgent"
	StartOnboardingOperation    OperationName = "StartOnboarding"
	SubmitContentOperation      OperationName = "SubmitContent"
	SubscribeSourceOperation    OperationName = "SubscribeSource"
)
