// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ApproveCliLink implements approveCliLink operation.
//
// Approve one pending CLI link session from the authenticated app.
//
// POST /api/agent/cli/link/{session_id}/approve
func (UnimplementedHandler) ApproveCliLink(ctx context.Context, req *CliLinkApproveRequest, params ApproveCliLinkParams) (r ApproveCliLinkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompleteOnboarding implements completeOnboarding operation.
//
// Complete onboarding from simplified selections.
//
// POST /api/agent/onboarding/{run_id}/complete
func (UnimplementedHandler) CompleteOnboarding(ctx context.Context, req *AgentOnboardingCompleteRequest, params CompleteOnboardingParams) (r CompleteOnboardingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ConvertNewsItemToArticle implements convertNewsItemToArticle operation.
//
// Convert one representative news item into saved article content.
//
// POST /api/news/items/{news_item_id}/convert-to-article
func (UnimplementedHandler) ConvertNewsItemToArticle(ctx context.Context, params ConvertNewsItemToArticleParams) (r ConvertNewsItemToArticleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgentLibraryFile implements getAgentLibraryFile operation.
//
// Return one rendered markdown document by relative manifest path.
//
// GET /api/agent/library/file
func (UnimplementedHandler) GetAgentLibraryFile(ctx context.Context, params GetAgentLibraryFileParams) (r GetAgentLibraryFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgentLibraryManifest implements getAgentLibraryManifest operation.
//
// Return manifest metadata for exportable per-user markdown files.
//
// GET /api/agent/library/manifest
func (UnimplementedHandler) GetAgentLibraryManifest(ctx context.Context, params GetAgentLibraryManifestParams) (r GetAgentLibraryManifestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetContentDetail implements getContentDetail operation.
//
// Retrieve detailed information about a specific content item.
//
// GET /api/content/{content_id}
func (UnimplementedHandler) GetContentDetail(ctx context.Context, params GetContentDetailParams) (r GetContentDetailRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetJob implements getJob operation.
//
// Return async job status.
//
// GET /api/jobs/{job_id}
func (UnimplementedHandler) GetJob(ctx context.Context, params GetJobParams) (r GetJobRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNewsItem implements getNewsItem operation.
//
// Return one visible representative news item.
//
// GET /api/news/items/{news_item_id}
func (UnimplementedHandler) GetNewsItem(ctx context.Context, params GetNewsItemParams) (r GetNewsItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOnboarding implements getOnboarding operation.
//
// Return onboarding run status.
//
// GET /api/agent/onboarding/{run_id}
func (UnimplementedHandler) GetOnboarding(ctx context.Context, params GetOnboardingParams) (r GetOnboardingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListContentSubmissionStatuses implements listContentSubmissionStatuses operation.
//
// Returns self-submitted content items that are not yet completed, including processing, failed, and
// skipped statuses.
//
// GET /api/content/submissions/list
func (UnimplementedHandler) ListContentSubmissionStatuses(ctx context.Context, params ListContentSubmissionStatusesParams) (r ListContentSubmissionStatusesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListContents implements listContents operation.
//
// Retrieve a list of content items with optional filtering by content type and date. Supports
// multiple content types via repeated query parameters (e.g.,
// ?content_type=article&content_type=podcast). Supports cursor-based pagination for efficient
// loading.
//
// GET /api/content/
func (UnimplementedHandler) ListContents(ctx context.Context, params ListContentsParams) (r ListContentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListNewsItems implements listNewsItems operation.
//
// Return the visible representative news feed for the current user.
//
// GET /api/news/items
func (UnimplementedHandler) ListNewsItems(ctx context.Context, params ListNewsItemsParams) (r ListNewsItemsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListScraperConfigs implements listScraperConfigs operation.
//
// List scraper configurations for the current user.
//
// GET /api/scrapers/
func (UnimplementedHandler) ListScraperConfigs(ctx context.Context, params ListScraperConfigsParams) (r ListScraperConfigsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MarkNewsItemsRead implements markNewsItemsRead operation.
//
// Mark the given visible representative news items as read.
//
// POST /api/news/items/mark-read
func (UnimplementedHandler) MarkNewsItemsRead(ctx context.Context, req *BulkMarkReadRequest) (r MarkNewsItemsReadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PollCliLink implements pollCliLink operation.
//
// Poll a pending CLI link session without requiring existing auth.
//
// GET /api/agent/cli/link/{session_id}
func (UnimplementedHandler) PollCliLink(ctx context.Context, params PollCliLinkParams) (r PollCliLinkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchAgent implements searchAgent operation.
//
// Search external/provider-backed sources for the agent CLI.
//
// POST /api/agent/search
func (UnimplementedHandler) SearchAgent(ctx context.Context, req *AgentSearchRequest) (r SearchAgentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StartCliLink implements startCliLink operation.
//
// Create an unauthenticated QR approval session for the CLI.
//
// POST /api/agent/cli/link/start
func (UnimplementedHandler) StartCliLink(ctx context.Context, req OptCliLinkStartRequest) (r StartCliLinkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StartOnboarding implements startOnboarding operation.
//
// Start simplified async onboarding.
//
// POST /api/agent/onboarding
func (UnimplementedHandler) StartOnboarding(ctx context.Context, req *AgentOnboardingStartRequest) (r StartOnboardingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SubmitContent implements submitContent operation.
//
// Submit article or podcast URLs for processing. Only http/https URLs are accepted.
//
// POST /api/content/submit
func (UnimplementedHandler) SubmitContent(ctx context.Context, req *SubmitContentRequest) (r SubmitContentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SubscribeScrapersToFeed implements subscribeScrapersToFeed operation.
//
// Subscribe to a feed detected from content.
// Convenience endpoint that creates a scraper config from a detected feed.
//
// POST /api/scrapers/subscribe
func (UnimplementedHandler) SubscribeScrapersToFeed(ctx context.Context, req *SubscribeToFeedRequest) (r SubscribeScrapersToFeedRes, _ error) {
	return r, ht.ErrNotImplemented
}
