// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *AgentLibraryManifestResponse) setDefaults() {
	{
		val := bool(true)
		s.IncludeSource.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AgentOnboardingCompleteRequest) setDefaults() {
	{
		val := bool(false)
		s.AcceptAll.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AgentSearchRequest) setDefaults() {
	{
		val := bool(true)
		s.IncludePodcasts.SetTo(val)
	}
	{
		val := int(10)
		s.Limit.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CliLinkStartResponse) setDefaults() {
	{
		val := int(2)
		s.PollIntervalSeconds.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ContentDetailResponse) setDefaults() {
	{
		val := bool(false)
		s.BodyAvailable.SetTo(val)
	}
	{
		val := bool(false)
		s.CanSubscribe.SetTo(val)
	}
	{
		val := bool(false)
		s.IsRead.SetTo(val)
	}
	{
		val := bool(false)
		s.IsSavedToKnowledge.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ContentSubmissionResponse) setDefaults() {
	{
		val := bool(false)
		s.AlreadyExists.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ContentSummaryResponse) setDefaults() {
	{
		val := bool(false)
		s.IsRead.SetTo(val)
	}
	{
		val := bool(false)
		s.IsSavedToKnowledge.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConvertNewsItemResponse) setDefaults() {
	{
		val := string("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DetectedFeed) setDefaults() {
	{
		val := string("rss")
		s.Format.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *JobStatusResponse) setDefaults() {
	{
		val := int(0)
		s.RetryCount.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OnboardingDiscoveryLaneStatus) setDefaults() {
	{
		val := int(0)
		s.CompletedQueries.SetTo(val)
	}
	{
		val := int(0)
		s.QueryCount.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OnboardingSuggestion) setDefaults() {
	{
		val := bool(false)
		s.IsDefault.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PaginationMetadata) setDefaults() {
	{
		val := bool(false)
		s.HasMore.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ScraperConfigStatsResponse) setDefaults() {
	{
		val := int(0)
		s.IntervalSampleSize.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SubmissionStatusResponse) setDefaults() {
	{
		val := bool(true)
		s.IsSelfSubmission.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SubmitContentRequest) setDefaults() {
	{
		val := bool(false)
		s.CrawlLinks.SetTo(val)
	}
	{
		val := bool(false)
		s.SaveToKnowledgeAndMarkRead.SetTo(val)
	}
	{
		val := bool(false)
		s.ShareAndChat.SetTo(val)
	}
	{
		val := bool(false)
		s.SubscribeToFeed.SetTo(val)
	}
}
