// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	ApproveCliLinkOperation                OperationName = "ApproveCliLink"
	CompleteOnboardingOperation            OperationName = "CompleteOnboarding"
	ConvertNewsItemToArticleOperation      OperationName = "ConvertNewsItemToArticle"
	GetAgentLibraryFileOperation           OperationName = "GetAgentLibraryFile"
	GetAgentLibraryManifestOperation       OperationName = "GetAgentLibraryManifest"
	GetContentDetailOperation              OperationName = "GetContentDetail"
	GetJobOperation                        OperationName = "GetJob"
	GetNewsItemOperation                   OperationName = "GetNewsItem"
	GetOnboardingOperation                 OperationName = "GetOnboarding"
	ListContentSubmissionStatusesOperation OperationName = "ListContentSubmissionStatuses"
	ListContentsOperation                  OperationName = "ListContents"
	ListNewsItemsOperation                 OperationName = "ListNewsItems"
	ListScraperConfigsOperation            OperationName = "ListScraperConfigs"
	MarkNewsItemsReadOperation             OperationName = "MarkNewsItemsRead"
	PollCliLinkOperation                   OperationName = "PollCliLink"
	SearchAgentOperation                   OperationName = "SearchAgent"
	StartCliLinkOperation                  OperationName = "StartCliLink"
	StartOnboardingOperation               OperationName = "StartOnboarding"
	SubmitContentOperation                 OperationName = "SubmitContent"
	SubscribeScrapersToFeedOperation       OperationName = "SubscribeScrapersToFeed"
)
