// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CompleteOnboarding implements completeOnboarding operation.
//
// Complete onboarding from simplified selections.
//
// POST /api/agent/onboarding/{run_id}/complete
func (UnimplementedHandler) CompleteOnboarding(ctx context.Context, req *AgentOnboardingCompleteRequest, params CompleteOnboardingParams) (r CompleteOnboardingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GenerateDigest implements generateDigest operation.
//
// Queue arbitrary-window digest generation for agent clients.
//
// POST /api/agent/digests
func (UnimplementedHandler) GenerateDigest(ctx context.Context, req *AgentDigestRequest) (r GenerateDigestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetContent implements getContent operation.
//
// Retrieve detailed information about a specific content item.
//
// GET /api/content/{content_id}
func (UnimplementedHandler) GetContent(ctx context.Context, params GetContentParams) (r GetContentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetJob implements getJob operation.
//
// Return async job status.
//
// GET /api/jobs/{job_id}
func (UnimplementedHandler) GetJob(ctx context.Context, params GetJobParams) (r GetJobRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOnboarding implements getOnboarding operation.
//
// Return onboarding run status.
//
// GET /api/agent/onboarding/{run_id}
func (UnimplementedHandler) GetOnboarding(ctx context.Context, params GetOnboardingParams) (r GetOnboardingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListContent implements listContent operation.
//
// Retrieve a list of content items with optional filtering by content type and date. Supports
// multiple content types via repeated query parameters (e.g.,
// ?content_type=article&content_type=podcast). Supports cursor-based pagination for efficient
// loading.
//
// GET /api/content/
func (UnimplementedHandler) ListContent(ctx context.Context, params ListContentParams) (r ListContentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDigests implements listDigests operation.
//
// List per-user daily digest rows.
//
// GET /api/content/daily-digests
func (UnimplementedHandler) ListDigests(ctx context.Context, params ListDigestsParams) (r ListDigestsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSources implements listSources operation.
//
// List scraper configurations for the current user.
//
// GET /api/scrapers/
func (UnimplementedHandler) ListSources(ctx context.Context, params ListSourcesParams) (r ListSourcesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchAgent implements searchAgent operation.
//
// Search external/provider-backed sources for the agent CLI.
//
// POST /api/agent/search
func (UnimplementedHandler) SearchAgent(ctx context.Context, req *AgentSearchRequest) (r SearchAgentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StartOnboarding implements startOnboarding operation.
//
// Start simplified async onboarding.
//
// POST /api/agent/onboarding
func (UnimplementedHandler) StartOnboarding(ctx context.Context, req *AgentOnboardingStartRequest) (r StartOnboardingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SubmitContent implements submitContent operation.
//
// Submit article or podcast URLs for processing. Only http/https URLs are accepted.
//
// POST /api/content/submit
func (UnimplementedHandler) SubmitContent(ctx context.Context, req *SubmitContentRequest) (r SubmitContentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SubscribeSource implements subscribeSource operation.
//
// Subscribe to a feed detected from content.
// Convenience endpoint that creates a scraper config from a detected feed.
//
// POST /api/scrapers/subscribe
func (UnimplementedHandler) SubscribeSource(ctx context.Context, req *SubscribeToFeedRequest) (r SubscribeSourceRes, _ error) {
	return r, ht.ErrNotImplemented
}
