// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *AgentDigestRequest) setDefaults() {
	{
		val := AgentDigestRequestForm("short")
		s.Form.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AgentDigestResponse) setDefaults() {
	{
		val := string("queued")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AgentOnboardingCompleteRequest) setDefaults() {
	{
		val := bool(false)
		s.AcceptAll.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AgentSearchRequest) setDefaults() {
	{
		val := bool(true)
		s.IncludePodcasts.SetTo(val)
	}
	{
		val := int(10)
		s.Limit.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ContentDetailResponse) setDefaults() {
	{
		val := bool(false)
		s.CanSubscribe.SetTo(val)
	}
	{
		val := bool(false)
		s.IsFavorited.SetTo(val)
	}
	{
		val := bool(false)
		s.IsRead.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ContentSubmissionResponse) setDefaults() {
	{
		val := bool(false)
		s.AlreadyExists.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ContentSummaryResponse) setDefaults() {
	{
		val := bool(false)
		s.IsFavorited.SetTo(val)
	}
	{
		val := bool(false)
		s.IsRead.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DailyNewsDigestResponse) setDefaults() {
	{
		val := bool(false)
		s.IsRead.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DetectedFeed) setDefaults() {
	{
		val := string("rss")
		s.Format.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *JobStatusResponse) setDefaults() {
	{
		val := int(0)
		s.RetryCount.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OnboardingDiscoveryLaneStatus) setDefaults() {
	{
		val := int(0)
		s.CompletedQueries.SetTo(val)
	}
	{
		val := int(0)
		s.QueryCount.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OnboardingSuggestion) setDefaults() {
	{
		val := bool(false)
		s.IsDefault.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PaginationMetadata) setDefaults() {
	{
		val := bool(false)
		s.HasMore.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SubmitContentRequest) setDefaults() {
	{
		val := bool(false)
		s.CrawlLinks.SetTo(val)
	}
	{
		val := bool(false)
		s.ShareAndChat.SetTo(val)
	}
	{
		val := bool(false)
		s.SubscribeToFeed.SetTo(val)
	}
}
