// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// ApproveCliLinkParams is parameters of approveCliLink operation.
type ApproveCliLinkParams struct {
	SessionID string
}

func unpackApproveCliLinkParams(packed middleware.Parameters) (params ApproveCliLinkParams) {
	{
		key := middleware.ParameterKey{
			Name: "session_id",
			In:   "path",
		}
		params.SessionID = packed[key].(string)
	}
	return params
}

func decodeApproveCliLinkParams(args [1]string, argsEscaped bool, r *http.Request) (params ApproveCliLinkParams, _ error) {
	// Decode path: session_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "session_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SessionID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     8,
					MinLengthSet:  true,
					MaxLength:     64,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.SessionID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "session_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CompleteOnboardingParams is parameters of completeOnboarding operation.
type CompleteOnboardingParams struct {
	RunID int
}

func unpackCompleteOnboardingParams(packed middleware.Parameters) (params CompleteOnboardingParams) {
	{
		key := middleware.ParameterKey{
			Name: "run_id",
			In:   "path",
		}
		params.RunID = packed[key].(int)
	}
	return params
}

func decodeCompleteOnboardingParams(args [1]string, argsEscaped bool, r *http.Request) (params CompleteOnboardingParams, _ error) {
	// Decode path: run_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "run_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.RunID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "run_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ConvertNewsItemToArticleParams is parameters of convertNewsItemToArticle operation.
type ConvertNewsItemToArticleParams struct {
	NewsItemID int
}

func unpackConvertNewsItemToArticleParams(packed middleware.Parameters) (params ConvertNewsItemToArticleParams) {
	{
		key := middleware.ParameterKey{
			Name: "news_item_id",
			In:   "path",
		}
		params.NewsItemID = packed[key].(int)
	}
	return params
}

func decodeConvertNewsItemToArticleParams(args [1]string, argsEscaped bool, r *http.Request) (params ConvertNewsItemToArticleParams, _ error) {
	// Decode path: news_item_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "news_item_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.NewsItemID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  true,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(params.NewsItemID)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "news_item_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetAgentLibraryFileParams is parameters of getAgentLibraryFile operation.
type GetAgentLibraryFileParams struct {
	Path string
}

func unpackGetAgentLibraryFileParams(packed middleware.Parameters) (params GetAgentLibraryFileParams) {
	{
		key := middleware.ParameterKey{
			Name: "path",
			In:   "query",
		}
		params.Path = packed[key].(string)
	}
	return params
}

func decodeGetAgentLibraryFileParams(args [0]string, argsEscaped bool, r *http.Request) (params GetAgentLibraryFileParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: path.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "path",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Path = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     1024,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.Path)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "path",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetAgentLibraryManifestParams is parameters of getAgentLibraryManifest operation.
type GetAgentLibraryManifestParams struct {
	IncludeSource OptBool `json:",omitempty,omitzero"`
}

func unpackGetAgentLibraryManifestParams(packed middleware.Parameters) (params GetAgentLibraryManifestParams) {
	{
		key := middleware.ParameterKey{
			Name: "include_source",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.IncludeSource = v.(OptBool)
		}
	}
	return params
}

func decodeGetAgentLibraryManifestParams(args [0]string, argsEscaped bool, r *http.Request) (params GetAgentLibraryManifestParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: include_source.
	{
		val := bool(true)
		params.IncludeSource.SetTo(val)
	}
	// Decode query: include_source.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "include_source",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIncludeSourceVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotIncludeSourceVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IncludeSource.SetTo(paramsDotIncludeSourceVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "include_source",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetContentDetailParams is parameters of getContentDetail operation.
type GetContentDetailParams struct {
	// Content ID.
	ContentID int
}

func unpackGetContentDetailParams(packed middleware.Parameters) (params GetContentDetailParams) {
	{
		key := middleware.ParameterKey{
			Name: "content_id",
			In:   "path",
		}
		params.ContentID = packed[key].(int)
	}
	return params
}

func decodeGetContentDetailParams(args [1]string, argsEscaped bool, r *http.Request) (params GetContentDetailParams, _ error) {
	// Decode path: content_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "content_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ContentID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  true,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(params.ContentID)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "content_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetJobParams is parameters of getJob operation.
type GetJobParams struct {
	JobID int
}

func unpackGetJobParams(packed middleware.Parameters) (params GetJobParams) {
	{
		key := middleware.ParameterKey{
			Name: "job_id",
			In:   "path",
		}
		params.JobID = packed[key].(int)
	}
	return params
}

func decodeGetJobParams(args [1]string, argsEscaped bool, r *http.Request) (params GetJobParams, _ error) {
	// Decode path: job_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "job_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.JobID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "job_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetNewsItemParams is parameters of getNewsItem operation.
type GetNewsItemParams struct {
	NewsItemID int
}

func unpackGetNewsItemParams(packed middleware.Parameters) (params GetNewsItemParams) {
	{
		key := middleware.ParameterKey{
			Name: "news_item_id",
			In:   "path",
		}
		params.NewsItemID = packed[key].(int)
	}
	return params
}

func decodeGetNewsItemParams(args [1]string, argsEscaped bool, r *http.Request) (params GetNewsItemParams, _ error) {
	// Decode path: news_item_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "news_item_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.NewsItemID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  true,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(params.NewsItemID)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "news_item_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetOnboardingParams is parameters of getOnboarding operation.
type GetOnboardingParams struct {
	RunID int
}

func unpackGetOnboardingParams(packed middleware.Parameters) (params GetOnboardingParams) {
	{
		key := middleware.ParameterKey{
			Name: "run_id",
			In:   "path",
		}
		params.RunID = packed[key].(int)
	}
	return params
}

func decodeGetOnboardingParams(args [1]string, argsEscaped bool, r *http.Request) (params GetOnboardingParams, _ error) {
	// Decode path: run_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "run_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.RunID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "run_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListContentSubmissionStatusesParams is parameters of listContentSubmissionStatuses operation.
type ListContentSubmissionStatusesParams struct {
	// Pagination cursor for next page.
	Cursor OptNilString `json:",omitempty,omitzero"`
	// Number of items per page (max 100).
	Limit OptInt `json:",omitempty,omitzero"`
}

func unpackListContentSubmissionStatusesParams(packed middleware.Parameters) (params ListContentSubmissionStatusesParams) {
	{
		key := middleware.ParameterKey{
			Name: "cursor",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cursor = v.(OptNilString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	return params
}

func decodeListContentSubmissionStatusesParams(args [0]string, argsEscaped bool, r *http.Request) (params ListContentSubmissionStatusesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: cursor.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cursor",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCursorVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCursorVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cursor.SetTo(paramsDotCursorVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cursor",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(25)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           100,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListContentsParams is parameters of listContents operation.
type ListContentsParams struct {
	// Filter by content type(s). Can be specified multiple times for multiple types
	// (article/podcast/news).
	ContentType OptNilStringArray `json:",omitempty,omitzero"`
	// Filter by date (YYYY-MM-DD format).
	Date OptNilString `json:",omitempty,omitzero"`
	// Filter by read status (all/read/unread).
	ReadFilter OptString `json:",omitempty,omitzero"`
	// Pagination cursor for next page.
	Cursor OptNilString `json:",omitempty,omitzero"`
	// Number of items per page (max 100).
	Limit OptInt `json:",omitempty,omitzero"`
	// Whether to include the available_dates metadata used by filterable list UIs. Disable for feed
	// surfaces that do not show date filters.
	IncludeAvailableDates OptBool `json:",omitempty,omitzero"`
}

func unpackListContentsParams(packed middleware.Parameters) (params ListContentsParams) {
	{
		key := middleware.ParameterKey{
			Name: "content_type",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ContentType = v.(OptNilStringArray)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "date",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Date = v.(OptNilString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "read_filter",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ReadFilter = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "cursor",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cursor = v.(OptNilString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "include_available_dates",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.IncludeAvailableDates = v.(OptBool)
		}
	}
	return params
}

func decodeListContentsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListContentsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: content_type.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "content_type",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotContentTypeVal []string
				if err := func() error {
					return d.DecodeArray(func(d uri.Decoder) error {
						var paramsDotContentTypeValVal string
						if err := func() error {
							val, err := d.DecodeValue()
							if err != nil {
								return err
							}

							c, err := conv.ToString(val)
							if err != nil {
								return err
							}

							paramsDotContentTypeValVal = c
							return nil
						}(); err != nil {
							return err
						}
						paramsDotContentTypeVal = append(paramsDotContentTypeVal, paramsDotContentTypeValVal)
						return nil
					})
				}(); err != nil {
					return err
				}
				params.ContentType.SetTo(paramsDotContentTypeVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.ContentType.Get(); ok {
					if err := func() error {
						if value == nil {
							return errors.New("nil is invalid value")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "content_type",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: date.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "date",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDateVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDateVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Date.SetTo(paramsDotDateVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Date.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     0,
							MaxLengthSet:  false,
							Email:         false,
							Hostname:      false,
							Regex:         regexMap["^\\d{4}-\\d{2}-\\d{2}$"],
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "date",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: read_filter.
	{
		val := string("all")
		params.ReadFilter.SetTo(val)
	}
	// Decode query: read_filter.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "read_filter",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotReadFilterVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotReadFilterVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ReadFilter.SetTo(paramsDotReadFilterVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.ReadFilter.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     0,
							MaxLengthSet:  false,
							Email:         false,
							Hostname:      false,
							Regex:         regexMap["^(all|read|unread)$"],
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "read_filter",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: cursor.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cursor",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCursorVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCursorVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cursor.SetTo(paramsDotCursorVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cursor",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(25)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           100,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: include_available_dates.
	{
		val := bool(true)
		params.IncludeAvailableDates.SetTo(val)
	}
	// Decode query: include_available_dates.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "include_available_dates",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIncludeAvailableDatesVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotIncludeAvailableDatesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IncludeAvailableDates.SetTo(paramsDotIncludeAvailableDatesVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "include_available_dates",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListNewsItemsParams is parameters of listNewsItems operation.
type ListNewsItemsParams struct {
	// Filter by read status.
	ReadFilter OptString `json:",omitempty,omitzero"`
	// Opaque cursor token.
	Cursor OptNilString `json:",omitempty,omitzero"`
	Limit  OptInt       `json:",omitempty,omitzero"`
}

func unpackListNewsItemsParams(packed middleware.Parameters) (params ListNewsItemsParams) {
	{
		key := middleware.ParameterKey{
			Name: "read_filter",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ReadFilter = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "cursor",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cursor = v.(OptNilString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	return params
}

func decodeListNewsItemsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListNewsItemsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: read_filter.
	{
		val := string("unread")
		params.ReadFilter.SetTo(val)
	}
	// Decode query: read_filter.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "read_filter",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotReadFilterVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotReadFilterVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ReadFilter.SetTo(paramsDotReadFilterVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.ReadFilter.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     0,
							MaxLengthSet:  false,
							Email:         false,
							Hostname:      false,
							Regex:         regexMap["^(all|read|unread)$"],
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "read_filter",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: cursor.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cursor",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCursorVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCursorVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cursor.SetTo(paramsDotCursorVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cursor",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(25)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           100,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListScraperConfigsParams is parameters of listScraperConfigs operation.
type ListScraperConfigsParams struct {
	Type         OptNilString `json:",omitempty,omitzero"`
	Types        OptNilString `json:",omitempty,omitzero"`
	IncludeStats OptBool      `json:",omitempty,omitzero"`
}

func unpackListScraperConfigsParams(packed middleware.Parameters) (params ListScraperConfigsParams) {
	{
		key := middleware.ParameterKey{
			Name: "type",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Type = v.(OptNilString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "types",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Types = v.(OptNilString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "include_stats",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.IncludeStats = v.(OptBool)
		}
	}
	return params
}

func decodeListScraperConfigsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListScraperConfigsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: type.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "type",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotTypeVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotTypeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Type.SetTo(paramsDotTypeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "type",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: types.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "types",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotTypesVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotTypesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Types.SetTo(paramsDotTypesVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "types",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: include_stats.
	{
		val := bool(true)
		params.IncludeStats.SetTo(val)
	}
	// Decode query: include_stats.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "include_stats",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIncludeStatsVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotIncludeStatsVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IncludeStats.SetTo(paramsDotIncludeStatsVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "include_stats",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// PollCliLinkParams is parameters of pollCliLink operation.
type PollCliLinkParams struct {
	SessionID string
	PollToken string
}

func unpackPollCliLinkParams(packed middleware.Parameters) (params PollCliLinkParams) {
	{
		key := middleware.ParameterKey{
			Name: "session_id",
			In:   "path",
		}
		params.SessionID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "poll_token",
			In:   "query",
		}
		params.PollToken = packed[key].(string)
	}
	return params
}

func decodePollCliLinkParams(args [1]string, argsEscaped bool, r *http.Request) (params PollCliLinkParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: session_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "session_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SessionID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     8,
					MinLengthSet:  true,
					MaxLength:     64,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.SessionID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "session_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: poll_token.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "poll_token",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.PollToken = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     8,
					MinLengthSet:  true,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.PollToken)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "poll_token",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
