// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CompleteOnboarding implements completeOnboarding operation.
	//
	// Complete onboarding from simplified selections.
	//
	// POST /api/agent/onboarding/{run_id}/complete
	CompleteOnboarding(ctx context.Context, req *AgentOnboardingCompleteRequest, params CompleteOnboardingParams) (CompleteOnboardingRes, error)
	// GenerateDigest implements generateDigest operation.
	//
	// Queue arbitrary-window digest generation for agent clients.
	//
	// POST /api/agent/digests
	GenerateDigest(ctx context.Context, req *AgentDigestRequest) (GenerateDigestRes, error)
	// GetContent implements getContent operation.
	//
	// Retrieve detailed information about a specific content item.
	//
	// GET /api/content/{content_id}
	GetContent(ctx context.Context, params GetContentParams) (GetContentRes, error)
	// GetJob implements getJob operation.
	//
	// Return async job status.
	//
	// GET /api/jobs/{job_id}
	GetJob(ctx context.Context, params GetJobParams) (GetJobRes, error)
	// GetOnboarding implements getOnboarding operation.
	//
	// Return onboarding run status.
	//
	// GET /api/agent/onboarding/{run_id}
	GetOnboarding(ctx context.Context, params GetOnboardingParams) (GetOnboardingRes, error)
	// ListContent implements listContent operation.
	//
	// Retrieve a list of content items with optional filtering by content type and date. Supports
	// multiple content types via repeated query parameters (e.g.,
	// ?content_type=article&content_type=podcast). Supports cursor-based pagination for efficient
	// loading.
	//
	// GET /api/content/
	ListContent(ctx context.Context, params ListContentParams) (ListContentRes, error)
	// ListDigests implements listDigests operation.
	//
	// List per-user daily digest rows.
	//
	// GET /api/content/daily-digests
	ListDigests(ctx context.Context, params ListDigestsParams) (ListDigestsRes, error)
	// ListSources implements listSources operation.
	//
	// List scraper configurations for the current user.
	//
	// GET /api/scrapers/
	ListSources(ctx context.Context, params ListSourcesParams) (ListSourcesRes, error)
	// SearchAgent implements searchAgent operation.
	//
	// Search external/provider-backed sources for the agent CLI.
	//
	// POST /api/agent/search
	SearchAgent(ctx context.Context, req *AgentSearchRequest) (SearchAgentRes, error)
	// StartOnboarding implements startOnboarding operation.
	//
	// Start simplified async onboarding.
	//
	// POST /api/agent/onboarding
	StartOnboarding(ctx context.Context, req *AgentOnboardingStartRequest) (StartOnboardingRes, error)
	// SubmitContent implements submitContent operation.
	//
	// Submit article or podcast URLs for processing. Only http/https URLs are accepted.
	//
	// POST /api/content/submit
	SubmitContent(ctx context.Context, req *SubmitContentRequest) (SubmitContentRes, error)
	// SubscribeSource implements subscribeSource operation.
	//
	// Subscribe to a feed detected from content.
	// Convenience endpoint that creates a scraper config from a detected feed.
	//
	// POST /api/scrapers/subscribe
	SubscribeSource(ctx context.Context, req *SubscribeToFeedRequest) (SubscribeSourceRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
