"""House visual theme for hosted Learning Deck viewing.

The deck HTML is generated by the sandbox agent, but its look is owned here so
every deck renders with one deliberate, responsive portrait-and-landscape
system instead of whatever theme the model improvised. The CSS is injected at
view time (see
``app.services.learning_deck_viewer.learning_deck_navigation_controls_html``),
so restyling a deck never requires regenerating it.

Design: "Daylight" — a near-white warm paper, zinc ink, a single desaturated
emerald accent, Space Grotesk display + Spline Sans body, and hairline rules
over boxes, sized for 9:16 portrait and 16:9 landscape canvases.

Keep this module free of f-strings: the CSS/JS below use literal ``{`` braces.
"""

from __future__ import annotations

from string import Template

from app.services.learning_deck_layout import learning_deck_prompt_values

DECK_THEME_STYLE_ID = "newsly-deck-theme"

# Google Fonts for the house type system. Stylesheet links are valid in <body>,
# so this can be injected alongside the view-time style block.
DECK_FONT_LINKS = (
    '<link rel="preconnect" href="https://fonts.googleapis.com">'
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
    '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?'
    "family=Space+Grotesk:wght@400;500;600;700&"
    "family=Spline+Sans:wght@400;500;600;700&"
    'family=Spline+Sans+Mono:wght@400;500;600&display=swap">'
)

DECK_THEME_CSS = """
:root {
  --paper: #fbfaf8;
  --paper-sunk: #f3f1ec;
  --ink: #1b1b1a;
  --ink-soft: #3c3c3a;
  --muted: #717170;
  --accent: #1f6f5c;
  --accent-strong: #16513f;
  --accent-soft: rgba(31, 111, 92, 0.10);
  --selection-bg: rgba(31, 111, 92, 0.26);
  --line: rgba(27, 27, 26, 0.12);
  --line-strong: rgba(27, 27, 26, 0.24);
  --code-bg: #15201c;
  --code-ink: #e9ede7;

  --font-display: "Space Grotesk", "Segoe UI", system-ui, sans-serif;
  --font-body: "Spline Sans", system-ui, -apple-system, "Segoe UI", sans-serif;
  --font-mono: "Spline Sans Mono", ui-monospace, "SFMono-Regular", Menlo, monospace;

  --r-background-color: var(--paper);
  --r-main-color: var(--ink);
  --r-heading-color: var(--ink);
  --r-link-color: var(--accent);
  --r-link-color-hover: var(--accent-strong);
  --r-link-color-dark: var(--accent-strong);
  --r-selection-background-color: var(--accent-soft);
  --r-selection-color: var(--ink);
  --r-main-font: var(--font-body);
  --r-heading-font: var(--font-display);
  --r-code-font: var(--font-mono);
  --r-heading-text-transform: none;
  --r-heading-font-weight: 600;
}

[data-deck-scheme="dark"] {
  --paper: #121413;
  --paper-sunk: #1b1e1c;
  --ink: #ecefea;
  --ink-soft: #cdd2cc;
  --muted: #8c938c;
  --accent: #54b89e;
  --accent-strong: #7fcdb6;
  --accent-soft: rgba(84, 184, 158, 0.14);
  --selection-bg: rgba(84, 184, 158, 0.32);
  --line: rgba(236, 239, 234, 0.14);
  --line-strong: rgba(236, 239, 234, 0.28);
  --code-bg: #0c100e;
  --code-ink: #e9ede7;
}

html, body, .reveal-viewport, .reveal { background: var(--paper); }

.reveal {
  font-family: var(--font-body);
  font-size: 30px;
  font-weight: 400;
  color: var(--ink);
  letter-spacing: -0.003em;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
.reveal ::selection {
  background: var(--selection-bg);
  color: var(--ink);
}

.reveal .slides { text-align: left; }
.reveal .slides section { padding: 42px 64px; }

.reveal h1, .reveal h2, .reveal h3, .reveal h4 {
  font-family: var(--font-display);
  color: var(--ink);
  font-weight: 600;
  line-height: 1.04;
  letter-spacing: -0.02em;
  margin: 0 0 0.34em;
  text-transform: none;
  text-wrap: balance;
}
.reveal h1 { font-size: 2.9em; }
.reveal h2 { font-size: 1.95em; }
.reveal h3 { font-size: 1.3em; letter-spacing: -0.01em; }
.reveal p { line-height: 1.5; margin: 0 0 0.7em; max-width: 64ch; }
.reveal strong { font-weight: 600; color: var(--ink); }
.reveal em { font-style: italic; }
.reveal a {
  color: var(--accent);
  text-decoration: none;
  border-bottom: 1px solid var(--accent-soft);
}
.reveal a:hover { color: var(--accent-strong); border-bottom-color: var(--accent); }
.reveal small, .reveal .muted { color: var(--muted); }

.reveal .eyebrow {
  font-family: var(--font-mono);
  font-size: 0.52em;
  font-weight: 600;
  letter-spacing: 0.22em;
  text-transform: uppercase;
  color: var(--accent);
  display: flex;
  align-items: center;
  gap: 0.9em;
  margin: 0 0 1.1em;
}
.reveal .eyebrow::after {
  content: "";
  flex: 0 0 auto;
  width: 2.6em;
  height: 2px;
  background: var(--accent);
  opacity: 0.55;
}

.reveal .rule {
  width: 64px;
  height: 3px;
  margin: 0.3em 0 0;
  border: 0;
  border-radius: 2px;
  background: var(--accent);
}

.reveal .lede {
  font-size: 1.16em;
  line-height: 1.4;
  color: var(--muted);
  max-width: 46ch;
  margin: 0.1em 0 0;
}

.reveal ul, .reveal .bullets { list-style: none; margin: 0.2em 0 0; padding: 0; max-width: 60ch; }
.reveal ul li, .reveal .bullets li {
  position: relative;
  padding-left: 1.5em;
  margin: 0.5em 0;
  line-height: 1.45;
}
.reveal ul li::before, .reveal .bullets li::before {
  content: "";
  position: absolute;
  left: 0;
  top: 0.62em;
  width: 0.7em;
  height: 2px;
  background: var(--accent);
}
.reveal ol { margin: 0.2em 0 0; padding-left: 1.5em; max-width: 60ch; }
.reveal ol li { margin: 0.5em 0; line-height: 1.45; }
.reveal ol li::marker { color: var(--accent); font-family: var(--font-mono); font-weight: 600; }
.reveal .bullets--cols { max-width: none; column-count: 2; column-gap: 64px; }
.reveal .bullets--cols li { break-inside: avoid; }

.reveal .slide--cover { display: flex; align-items: center; gap: 56px; width: 100%; }
.reveal .cover__text { flex: 1 1 56%; }
.reveal .cover__text h1 { font-size: 3.3em; margin-bottom: 0.2em; }
.reveal .cover__art { flex: 1 1 44%; position: relative; }
.reveal .cover__art img {
  width: 100%;
  height: 520px;
  object-fit: cover;
  border-radius: 18px;
}
.reveal .slide--split { display: flex; align-items: center; gap: 72px; width: 100%; }
.reveal .split__text { flex: 1 1 50%; }
.reveal .split__art { flex: 1 1 50%; }
.reveal .slide--split.is-media-led .split__text { flex-basis: 38%; }
.reveal .slide--split.is-media-led .split__art { flex-basis: 62%; }
.reveal .split__art img { width: 100%; max-height: 540px; object-fit: cover; }

.reveal section.slide--section h2 { font-size: 2.6em; max-width: 18ch; }

.reveal .statement {
  font-family: var(--font-display);
  font-weight: 500;
  font-size: 2.3em;
  line-height: 1.12;
  letter-spacing: -0.018em;
  max-width: 20ch;
  color: var(--ink);
  margin: 0;
}

.reveal img {
  display: block;
  max-width: 100%;
  height: auto;
  border-radius: 14px;
  outline: 1px solid var(--line);
  box-shadow: 0 24px 48px -28px rgba(27, 27, 26, 0.4);
}
.reveal figure { margin: 0; }
.reveal figure figcaption {
  font-family: var(--font-mono);
  font-size: 0.6em;
  color: var(--muted);
  margin-top: 0.7em;
  letter-spacing: 0.02em;
}

.reveal blockquote {
  background: none;
  box-shadow: none;
  border: 0;
  border-left: 3px solid var(--accent);
  margin: 0.3em 0;
  padding: 0.1em 0 0.1em 1em;
  width: auto;
  max-width: 26ch;
  font-family: var(--font-display);
  font-style: italic;
  font-weight: 500;
  font-size: 1.5em;
  line-height: 1.22;
  color: var(--ink);
}
.reveal blockquote cite, .reveal blockquote footer {
  display: block;
  margin-top: 0.5em;
  font-family: var(--font-mono);
  font-style: normal;
  font-size: 0.5em;
  letter-spacing: 0.04em;
  color: var(--muted);
}

.reveal pre { width: 100%; margin: 0.4em 0; box-shadow: none; font-size: 0.56em; }
.reveal code { font-family: var(--font-mono); }
.reveal :not(pre) > code {
  background: var(--accent-soft);
  color: var(--accent-strong);
  border-radius: 6px;
  padding: 0.08em 0.35em;
  font-size: 0.92em;
}
.reveal pre code {
  background: var(--code-bg);
  color: var(--code-ink);
  border-radius: 14px;
  border: 1px solid rgba(255, 255, 255, 0.06);
  padding: 24px 26px;
  line-height: 1.5;
  max-height: 520px;
}
.reveal pre code .hljs-keyword, .reveal pre code .hljs-selector-tag,
.reveal pre code .hljs-built_in { color: var(--accent); }
.reveal pre code .hljs-string, .reveal pre code .hljs-attr,
.reveal pre code .hljs-addition { color: var(--code-ink); }
.reveal pre code .hljs-comment, .reveal pre code .hljs-quote {
  color: #7b857d;
  font-style: italic;
}
.reveal pre code .hljs-number, .reveal pre code .hljs-literal { color: var(--code-ink); }
.reveal pre code .hljs-title,
.reveal pre code .hljs-section { color: var(--code-ink); font-weight: 600; }

.reveal table { border-collapse: collapse; width: 100%; font-size: 0.78em; margin: 0.3em 0; }
.reveal table th, .reveal table td {
  padding: 0.55em 0.8em;
  text-align: left;
  border: 0;
  border-bottom: 1px solid var(--line);
}
.reveal table th {
  font-family: var(--font-mono);
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  font-size: 0.82em;
  color: var(--muted);
}

.reveal .progress { color: var(--accent); height: 3px; }
.reveal .slide-number {
  background: transparent;
  color: var(--muted);
  font-family: var(--font-mono);
  font-size: 14px;
  letter-spacing: 0.04em;
  right: 22px;
  bottom: 18px;
}

html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal {
  font-size: 32px;
}
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait
  .reveal .slides section:not(.stack) {
  height: 100%;
  padding: 54px 48px 92px;
}
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal h1 {
  font-size: 2.35em;
}
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal h2 {
  font-size: 1.78em;
}
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal .lede {
  font-size: 1.08em;
  max-width: 34ch;
}
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal .slide-frame {
  display: flex;
  height: 100%;
  flex-direction: column;
  justify-content: space-between;
  gap: 32px;
}
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal .slide--cover,
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal .slide--split {
  height: 100%;
  flex-direction: column;
  align-items: stretch;
  justify-content: center;
  gap: 40px;
}
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait
  .reveal section.slide--section,
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait
  .reveal section.slide--statement {
  display: flex !important;
  flex-direction: column;
  justify-content: center;
}
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal .cover__text,
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal .cover__art,
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal .split__text,
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal .split__art,
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait
  .reveal .slide--split.is-media-led .split__text,
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait
  .reveal .slide--split.is-media-led .split__art {
  flex: 0 0 auto;
}
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal .cover__art img,
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal .split__art img {
  width: 100%;
  height: auto;
  max-height: 480px;
  object-fit: contain;
}
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal .bullets--cols {
  column-count: 1;
}
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal table {
  font-size: 0.72em;
}
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal pre code {
  max-height: 620px;
}
html.newsly-learning-deck-responsive.newsly-learning-deck-portrait .reveal .statement {
  max-width: 15ch;
  font-size: 2.12em;
}

@media (prefers-reduced-motion: no-preference) {
  .reveal .slides section.present > * {
    animation: deckRise 0.5s cubic-bezier(0.16, 1, 0.3, 1) both;
  }
  .reveal .slides section.present > *:nth-child(2) { animation-delay: 0.05s; }
  .reveal .slides section.present > *:nth-child(3) { animation-delay: 0.1s; }
  .reveal .slides section.present > *:nth-child(4) { animation-delay: 0.15s; }
  .reveal .slides section.present > *:nth-child(5) { animation-delay: 0.2s; }
  @keyframes deckRise {
    from { opacity: 0; transform: translateY(14px); }
    to { opacity: 1; transform: none; }
  }
}
"""


_DECK_DESIGN_GUIDE_TEMPLATE = """## House visual system (Daylight) — applied automatically

A deliberate house theme is injected when the deck is viewed: the **Daylight**
system. You do NOT need to design a color theme, choose fonts, or set the Reveal
width/height — that is handled for you and will override anything you add. Spend
your effort on clear teaching structure and the right layout per slide.

The house system (for reference, so your accents match):
- Surface: warm near-white paper `#fbfaf8`; ink `#1b1b1a`; muted `#717170`.
- One accent only: desaturated emerald `#1f6f5c`. Use it sparingly for rules,
  eyebrows, links, and markers. No second accent, no gradients, no glows.
- Type: Space Grotesk (display) + Spline Sans (body) + Spline Sans Mono (code).
- Canvas: responsive $portrait_canvas portrait and $landscape_canvas landscape compositions, with
  content left-aligned and distributed through the available height.

### Author slides with these house classes

Use semantic Reveal sections and the house classes below; the theme styles them. Use a
`class="slide-frame"` wrapper for ordinary content slides that should distribute a heading and main
teaching object through the portrait height.
Do not center body text, and do not wrap every slide in a card.

- Cover (first slide), asymmetric text + inset image:
  ```html
  <section>
    <div class="slide--cover">
      <div class="cover__text">
        <p class="eyebrow">Learning deck</p>
        <h1>Concrete, specific title</h1>
        <p class="lede">One-line framing of what the learner will get.</p>
      </div>
      <div class="cover__art"><img src="..." alt="..."></div>
    </div>
  </section>
  ```
  Omit `cover__art` if you have no strong, relevant image.

- Section divider:
  ```html
  <section class="slide--section">
    <p class="eyebrow">Part 02</p>
    <h2>Where the next idea begins</h2>
    <div class="rule"></div>
  </section>
  ```

- Content (default): an `eyebrow`, an `h2`, an optional `lede`, then a `<ul>`.
  Keep bullets short (aim for under ~7 words). Use `class="bullets--cols"` on the
  `<ul>` only when you genuinely have many short items.

- Split (text beside a diagram, image, table, or code):
  ```html
  <section>
    <div class="slide--split">
      <div class="split__text">
        <p class="eyebrow">Topic</p>
        <h2>Heading</h2>
        <ul><li>Point</li></ul>
      </div>
      <div class="split__art"><img src="..." alt="..."></div>
    </div>
  </section>
  ```
  Add `is-media-led` to `slide--split` to give the media the larger column.

- Statement (a single key takeaway):
  ```html
  <section class="slide--statement">
    <p class="eyebrow">Takeaway</p>
    <p class="statement">The one thing to remember.</p>
  </section>
  ```

### Anti-slop rules

- No emojis or clip art anywhere.
- Left-aligned and asymmetric, not everything centered.
- One idea per slide; vary the layout on consecutive slides.
- No invented stats, fake names, or placeholder image services. Use a real image
  only when it teaches (the source figure, repo, product, architecture); a
  hand-built SVG/CSS/table diagram is better than decoration.
- Prefer hairline rules and negative space over boxes, drop shadows, and cards.
- Put exhaustive detail in source-notes, not on the slides.

### Reveal requirements (still your job)

- Load Reveal core CSS + JS and the highlight, notes, and markdown plugins from
  the allowed Reveal CDN, then call `Reveal.initialize(...)`.
- Put `$responsive_layout_meta_tag` in the document `<head>` so the
  hosted viewer selects the responsive portrait canvas.
- Include a `<style>` block (it can be minimal — the house theme is layered on at
  view time and wins).
- No inline event-handler attributes (onclick/onload); wire any JS with
  `addEventListener`.
"""

DECK_DESIGN_GUIDE = Template(_DECK_DESIGN_GUIDE_TEMPLATE).substitute(learning_deck_prompt_values())
