"""Curated production-backed clustering regression families."""

# ruff: noqa: E501

from __future__ import annotations

PRODUCTION_CLUSTER_CASES = [
    {
        "case_id": "batch_004_c6",
        "label": "Pentagon pressures Anthropic / supply chain risk dispute",
        "titles": [
            "Pentagon flags Anthropic as a supply chain risk, Bloomberg reports",
            "Pentagon threatens to cut off Anthropic contract over disputed AI safeguard requirements",
            "Pentagon threatens to make Anthropic a pariah if it refuses to drop AI guardrails | CNN Business",
            "Pentagon weighs cutting ties with Anthropic, may label AI firm a supply chain risk",
            "Pentagon pressures Anthropic to drop Claude Gov restrictions, threatens DPA action or “supply chain risk” label",
            "Pentagon gives Anthropic deadline to allow unrestricted military AI use or risk losing contract",
            "Pentagon chief Hegseth to meet Anthropic CEO as military AI rollout sparks ethics fight",
            "Pentagon CTO says Anthropic’s Claude would ‘pollute’ DOD supply chain, cites baked-in policy bias",
            "Pentagon offers written assurances to Anthropic as deadline looms for unrestricted Claude use",
            "Pentagon talks with Anthropic reportedly faltered over bulk data analysis of Americans",
            "Sen. Ron Wyden vows fight after Pentagon moves to bar Anthropic",
            "Pentagon-linked account calls to label Anthropic a supply-chain risk after public dispute",
        ],
    },
    {
        "case_id": "batch_001_c33",
        "label": "Anthropic refuses Pentagon unrestricted use",
        "titles": [
            "Anthropic fights Pentagon “any lawful use” clause as DoD threatens ‘supply chain risk’ label",
            "Anthropic ditches its core safety promise in the middle of an AI red line fight with the Pentagon | CNN Business",
            "Anthropic says it won’t remove safeguards on domestic surveillance and fully autonomous weapons for DoW",
            "Anthropic refuses Pentagon demand for unrestricted Claude use, citing surveillance and autonomous weapons risks",
            "Anthropic rejects latest Pentagon offer, ‘we cannot in good conscience accede to their request.’ | CNN Business",
            "Anthropic to challenge proposed Pentagon ‘supply chain risk’ label over surveillance, autonomous weapons",
            "Anthropic Hits Back After US Military Labels It a 'Supply Chain Risk' | WIRED",
            "Anthropic CEO holds firm on AI ‘red lines’ after Trump orders Pentagon to drop Claude",
            "Anthropic CEO says refusing Pentagon terms is free speech; vows court challenge if blacklisted",
            "Anthropic rejects Pentagon 'any lawful use' terms, risking $200M DoD contract over AI safeguards",
            "Anthropic refuses Pentagon “all lawful purposes” clause; ban triggers surge and forces OpenAI safeguards",
        ],
    },
    {
        "case_id": "batch_004_c1",
        "label": "OpenAI testing ads in ChatGPT",
        "titles": [
            "OpenAI targets ~$60 CPM for ChatGPT ads, matching NFL rates while offering little conversion data",
            "OpenAI Tests Ad Integration in ChatGPT Platform",
            "OpenAI to test ads in ChatGPT's free and $8 'Go' tiers as it burns through billions",
            "OpenAI to Test Ads in ChatGPT, Matched to Conversations, Says It Won't Sell User Data",
            "OpenAI to test ads under ChatGPT replies for free and Go users in US; targets 'low billions' in 2026",
            "OpenAI to Test Targeted Ads for Free ChatGPT Users — What to Expect",
            "OpenAI tests ChatGPT Ads Manager as early campaign performance trails Google Search",
        ],
    },
    {
        "case_id": "batch_004_c7",
        "label": "Pentagon used Anthropic Claude in Iran strikes via Palantir Maven",
        "titles": [
            "Pentagon used Palantir Maven with Anthropic Claude to hit 1,000 Iran targets in 24 hours",
            "Pentagon used Palantir Maven with Anthropic’s Claude to rapidly prioritize targets in Iran strikes",
            "Report: Anthropic’s Claude helped generate 1,000+ Iran strike targets via Palantir’s Maven system",
            "Report: Archived intel in AI targeting system may have caused strike on Iran girls’ school",
            "Reports: US military used Anthropic’s Claude AI in Iran strikes, then banned it hours later",
            "Report: US military used Anthropic’s Claude in Iran strikes hours after Trump ordered ban",
            "Report: US used Anthropic’s Claude via Palantir in raid to seize Venezuela’s Maduro",
        ],
    },
    {
        "case_id": "batch_001_c34",
        "label": "Anthropic sues Pentagon/Trump over blacklist",
        "titles": [
            "Anthropic sues Trump administration to overturn Pentagon 'supply chain risk' blacklist",
            "Anthropic Claims Pentagon Feud Could Cost It Billions | WIRED",
            "Anthropic sues US over Pentagon “supply chain risk” label, raising uncertainty around $380B valuation talk",
            "Anthropic sues Trump administration over Pentagon ‘supply chain risk’ label and Claude ban",
            "Anthropic sues Pentagon over AI ban tied to refusal to allow autonomous lethal use and mass surveillance",
            "Anthropic sues Pentagon over AI guardrails as Silicon Valley shifts toward defense work",
        ],
    },
    {
        "case_id": "batch_001_c82",
        "label": "Anthropic Cowork launch",
        "titles": [
            "Anthropic's Cowork preview lets Claude access and edit local files to automate multi-step work",
            "Anthropic's Cowork lets Claude automate complex tasks — powerful automation with clear security risks",
            "Anthropic's Claude Cowork brings Claude Code power to wider users, but prompt-injection risks remain",
            "Anthropic's Cowork brings Claude Code automation to non-coders on the desktop",
            "Claude Cowork brings Claude Code's agent power to non-developers via sandboxed macOS UI",
            "Anthropic opens Claude Cowork to $20/month Pro users, expanding autonomous Mac tasks",
        ],
    },
    {
        "case_id": "batch_002_c16",
        "label": "Discord age verification rollout and backlash",
        "titles": [
            "Discord Clarifies Age Verification Won't Affect Most Users",
            "Discord delays global age verification rollout to H2 2026 after backlash, adds more options",
            "Discord drops Persona after researchers find identity-verification code exposed on government endpoints",
            "Discord ends UK Persona age-check test after backlash, leans on k-ID as global rollout nears",
            "Discord mandates age verification; users flee to federated Matrix alternative",
            "Discord requires face scan or ID for adult access starting March",
        ],
    },
    {
        "case_id": "batch_003_c107",
        "label": "OpenAI Sora shutdown",
        "titles": [
            "OpenAI Announces Shutdown of Sora AI Video Platform",
            "OpenAI Kills Sora Project to Reallocate GPUs for Core Coding and Enterprise Products",
            "OpenAI Shuts Down Sora AI Video App Following Collapsed $1B Disney Deal",
            "OpenAI Shuts Down Sora Video Platform; Disney Cancels $1 Billion Partnership",
            "OpenAI Shuts Down Sora, Prompting Disney to Cancel $1 Billion Investment Deal",
            "OpenAI Discontinues Sora Video Tool and Scraps Major Disney Partnership",
        ],
    },
    {
        "case_id": "batch_003_c18",
        "label": "Jury finds Meta liable child safety",
        "titles": [
            "Jury finds Instagram, YouTube designed to addict children in landmark liability verdict",
            "Jury Finds Meta and YouTube Negligent in Landmark Social Media Addiction Trial",
            "Jury Finds Meta Knowingly Harmed Children for Profit, Awards $375 Million Verdict",
            "Jury finds Meta liable in case over child sexual exploitation on its platforms | CNN Business",
            "New Mexico Jury Orders Meta to Pay $375 Million Over Child Safety Law Violations",
            "Jury Begins Deliberations in Landmark New Mexico Trial Over Children’s Safety on Meta Platforms",
        ],
    },
    {
        "case_id": "batch_003_c24",
        "label": "Kimi K2.5 multimodal model release",
        "titles": [
            "Kimi K2.5: Open-source multimodal SOTA with agent swarms that cut runtime up to 4.5×",
            "Kimi K2.5: Pretrained on ~15T visual+text tokens and can self-direct 100-agent swarms",
            "Moonshot unveils K2.5 multimodal AI that handles text, images and video and beats open-source peers",
            "Moonshot says Kimi K2.5 builds on K2 with \"pretraining over ~15T mixed visual and text tokens\" and \"can self-direct an agent swarm with up to 100 sub-agents\" (Kimi)",
            "Moonshot Kimi K2.5 Released: 32B Active Parameter Model Claims SOTA Over Sonnet 4.5 with 100-Agent Swarms",
            "Kimi K2.5 Achieves Highest ECI Score Among Open-Weight AI Models",
        ],
    },
    {
        "case_id": "batch_004_c5",
        "label": "SpaceX acquires/merges with xAI",
        "titles": [
            "SpaceX acquires xAI to build orbital data‑center constellation and scale space-based AI",
            "SpaceX acquires xAI, plans up to 1 million satellites as orbital AI data centers",
            "SpaceX Acquires xAI, Pursues Solar-Powered AI Data Centers in Orbit",
            "SpaceX to combine with xAI ahead of mega IPO, consolidating Musk's AI and aerospace assets",
            "Sources: SpaceX in advanced talks to combine with xAI, briefed investors",
            "Sources: SpaceX in advanced talks to merge with xAI as Musk consolidates his empire",
        ],
    },
    {
        "case_id": "batch_001_c13",
        "label": "Bandcamp bans AI-generated music",
        "titles": [
            "Bandcamp bans AI-generated music and training on uploads to protect human artists",
            "Bandcamp bans AI-generated music to reassure fans and protect human artists",
            "Bandcamp bans music and audio that is \"generated wholly or in substantial part by AI\", hoping to build trust with fans that the music they find was human-made (Maya Perez/WebProNews)",
            "Bandcamp bans purely AI-generated music to protect human artists",
            "Bandcamp Bars AI-Generated Music, Raising Copyright and Moderation Stakes",
        ],
    },
    {
        "case_id": "batch_001_c14",
        "label": "Anthropic Claude Opus 4.6 launch",
        "titles": [
            "Anthropic launches Claude Opus 4.6 with 1M-token context and major agentic coding gains",
            "Anthropic's Claude Opus 4.6 targets complex financial research, now used by 300K+ businesses",
            "Anthropic's Opus 4.6 adds 'agent teams', 1M-token context window and PowerPoint Claude pane",
            "Anthropic's Claude Opus 4.6 targets first‑try enterprise work with 1M context and 90.2 BigLaw score",
            "Anthropic’s Claude Opus 4.6 reportedly uncovered 500 zero-day flaws in open-source code",
        ],
    },
    {
        "case_id": "batch_001_c32",
        "label": "CISA director uploaded sensitive docs to ChatGPT",
        "titles": [
            "Acting CISA chief accidentally uploaded sensitive 'For Official Use Only' docs to ChatGPT, prompting DHS probe",
            "CISA acting director uploaded sensitive 'for official use only' files to public ChatGPT, prompting DHS review",
            "Acting US cybersecurity chief reportedly uploaded sensitive government files to ChatGPT",
            "CISA interim director reportedly uploaded sensitive documents to ChatGPT, triggering alerts",
            "CISA Director Uploaded Classified Data to ChatGPT While Agency Loses Third of Staff",
        ],
    },
    {
        "case_id": "batch_001_c36",
        "label": "Anthropic alleges mass Claude distillation",
        "titles": [
            "Anthropic announces proof of distillation at scale by MiniMax, DeepSeek,Moonshot",
            "Anthropic says DeepSeek, Moonshot AI and MiniMax ran mass campaigns to distill Claude via 24,000 fake accounts",
            "Anthropic alleges industrial-scale Claude distillation as evals, agent engineering, and infra shift under pressure",
            "Anthropic alleges industrial-scale Claude distillation by Chinese labs, but impact is uneven and hard to police",
            "Anthropic says overseas labs ran 'industrial-scale' distillation to copy Claude via 16M API exchanges",
        ],
    },
    {
        "case_id": "batch_001_c45",
        "label": "Block cuts ~4,000 jobs citing AI",
        "titles": [
            "Block to cut over 4,000 jobs, nearly halving workforce; shares jump 24% after earnings",
            "Block to cut nearly half its workforce, shrinking from 10,000+ staff to under 6,000",
            "Block to cut 4,000 jobs, telling investors AI lets a smaller workforce “do more and better”",
            "Block cuts 40% of staff as Dorsey says AI tools are already replacing jobs",
            "Block cuts 4,000 jobs citing AI-driven efficiency; Dorsey says most firms will follow within a year",
        ],
    },
    {
        "case_id": "batch_001_c56",
        "label": "Arm launches AGI CPU for data centers",
        "titles": [
            "Arm Debuts 'AGI CPU' Silicon with 136 Cores for AI Infrastructure",
            "Arm Launches First In-House 'AGI CPU' for Agentic AI Infrastructure",
            "Arm Debuts First Proprietary AGI CPU for Data Centers with Up to 136 Cores",
            "Arm Enters Silicon Market with 136-Core AGI CPU for AI Infrastructure",
            "Arm Stock Jumps 6% as CEO Targets $25B in Revenue by 2031 with New In-House Chip",
        ],
    },
    {
        "case_id": "batch_001_c90",
        "label": "Chardet LGPL-to-MIT relicensing dispute",
        "titles": [
            "chardet rewrote its codebase with Claude and relicensed from LGPL to MIT, raising AI clean-room doubts",
            "chardet author disputes maintainers’ attempt to relicense project in v7.0.0 rewrite",
            "AI-driven rewrite of Python’s Chardet sparks dispute over shifting license from LGPL to MIT",
            "AI reimplementation of chardet triggers LGPL-to-MIT relicensing fight over copyleft legitimacy",
            "Chardet relicensing fight spotlights how AI rewrites could undermine copyleft and proprietary software",
        ],
    },
    {
        "case_id": "batch_002_c67",
        "label": "Grok deepfake/nudify controversy",
        "titles": [
            "Grok fuels surge of AI sexual content on X, exposing weak safety controls",
            "Grok generated thousands of sexualized deepfakes — including minors — prompting global probes and platform limits",
            "Grok geoblocked from undressing real people in places where it's illegal after global backlash",
            "Grok still generates sexualized, nearly nude images of men despite X's ban",
            "Grok lawyers tell Dutch court zero-abuse prevention is impossible in nudify tools case",
        ],
    },
    {
        "case_id": "batch_003_c101",
        "label": "OpenAI $110B round at $730B valuation",
        "titles": [
            "OpenAI closes record $110B round at $730B valuation as Amazon, Nvidia and SoftBank pile in",
            "OpenAI lands $110B round at $730B pre-money, deepening AWS and Nvidia infrastructure ties",
            "OpenAI raises $110B led by Amazon, NVIDIA and SoftBank, valuing company at $730B pre-money",
            "OpenAI Nears $10B Funding Deal at $730B Valuation with MGX, Coatue, and Thrive",
            "OpenAI Reportedly Nears $10B Funding Deal at $730B Valuation",
        ],
    },
    {
        "case_id": "batch_003_c102",
        "label": "OpenAI GPT-5.3-Codex launch",
        "titles": [
            "OpenAI releases GPT-5.3‑Codex — faster, agentic coding model that builds, debugs and runs software end-to-end",
            "OpenAI launches GPT-5.3-Codex — 25% faster, self‑helping agent expands beyond coding",
            "OpenAI Releases GPT-5.3-Codex with 25% Speed Boost and Benchmark Gains",
            "OpenAI announces GPT-5.3-Codex-Spark with enhanced capabilities",
            "OpenAI launches GPT-5.3-Codex-Spark using Cerebras chip technology",
        ],
    },
    {
        "case_id": "batch_003_c103",
        "label": "OpenAI GPT-5.4 launch",
        "titles": [
            "OpenAI launches GPT-5.4 for pro workflows, adding native computer-use and higher API prices",
            "OpenAI launches GPT-5.4 with native computer control, aiming at more autonomous AI agents",
            "OpenAI launches GPT-5.4 with Pro and Thinking models, adds 1M-token API context and cheaper tool calling",
            "OpenAI launches GPT-5.4 with 1M-token context and native computer-use for AI agents",
            "OpenAI launches GPT-5.4 mini and nano, bringing near-flagship results at much lower cost",
        ],
    },
    {
        "case_id": "batch_003_c72",
        "label": "Musk xAI restructuring co-founder exits",
        "titles": [
            "Musk reorganizes xAI amid co-founder exodus and regulatory scrutiny",
            "Musk Restructures xAI After Co-Founder Exits, Reorganizes Into Four Units",
            "Musk pitches lunar AI factory as xAI loses half its founding team before IPO",
            "Musk says xAI was 'not built right' as Tesla’s $2B stake draws fresh scrutiny",
            "Musk says xAI “wasn’t built right” as cofounders and engineers exit and “Macrohard” stalls",
        ],
    },
    {
        "case_id": "batch_003_c75",
        "label": "NanoClaw AI agent security",
        "titles": [
            "NanoClaw adds one-command Docker Sandboxes setup to isolate AI agents in micro VMs",
            "NanoClaw argues AI agents must be treated as hostile: isolate each agent in ephemeral containers",
            "NanoClaw goes from weekend security fix to Docker deal after viral Hacker News and Karpathy boost",
            "NanoClaw Integrates OneCLI Agent Vault to Secure AI Credentials and Enforce Policies",
            "NanoClaw: Lightweight personal Claude assistant using Apple container sandboxes",
        ],
    },
    {
        "case_id": "batch_003_c9",
        "label": "Iran internet blackout/bypass",
        "titles": [
            "Iran's precise internet shutdown cuts 90% of traffic and could be prolonged",
            "Iran's temporary blackout risks becoming a permanent, elite-only tiered internet",
            "Iran’s near-total internet blackout shifts to whitelisting, enabling selective access while isolating 90M people",
            "Iranians bypass near-total blackout with smuggled Starlinks and bespoke software",
            "Iranians use Starlink, VPNs and decentralized apps to bypass near-total internet blackout",
        ],
    },
    {
        "case_id": "batch_003_c90",
        "label": "Nvidia NemoClaw enterprise agent platform",
        "titles": [
            "Nvidia launches NemoClaw: an enterprise OpenClaw stack with policy-based security guardrails",
            "Nvidia Is Planning to Launch an Open-Source AI Agent Platform | WIRED",
            "Nvidia readies open-source NemoClaw platform to manage enterprise AI agents amid “OpenClaw” surge",
            "Nvidia reportedly readies open-source enterprise AI agent platform ‘NemoClaw’ with security tools",
            "NVIDIA open-sources NemoClaw to sandbox OpenClaw assistants via OpenShell with policy-controlled egress",
        ],
    },
    {
        "case_id": "batch_003_c91",
        "label": "Nvidia investment in OpenAI",
        "titles": [
            "Nvidia in talks to invest up to $30B in OpenAI at reported $730B pre-money valuation",
            "Nvidia near $20B investment in OpenAI to anchor $100B funding round",
            "Nvidia will join OpenAI's current funding round but not with a $100B stake, Huang says",
            "Nvidia’s Huang says $30B OpenAI stake may be its last as OpenAI prepares to go public",
            "Nvidia’s Jensen Huang rules out $100 billion OpenAI investment, Bloomberg reports",
        ],
    },
    {
        "case_id": "batch_005_c25",
        "label": "Yann LeCun AMI Labs $1B raise",
        "titles": [
            "Yann LeCun launches Paris-based AMI Labs to bet on world models over LLMs",
            "Yann LeCun Raises $1 Billion to Build AI That Understands the Physical World | WIRED",
            "Yann LeCun’s AMI Labs lands $1.03B to pursue ‘world models’ beyond LLMs",
            "Yann LeCun’s AMI Labs raises $1.03B seed to pursue JEPA-based world models, challenging LLM-first orthodoxy",
            "Yann LeCun’s Startup Just Raised Over $1 Billion - Why That Matters — abZ Global",
        ],
    },
    {
        "case_id": "batch_001_c117",
        "label": "Anthropic Claude Code leak",
        "titles": [
            "Claude Code Leak Points to Always-On Agents, Auto-Approvals, and Stealth Open-Source Work",
            "Claude Code’s Edge Appears to Be Its Harness, Not Just Claude",
            "Claude Code’s Source Reveals a Configurable Agent Orchestrator, Not a Simple Terminal Chat",
            "Claude Code Leak Exposes Agent Architecture, Memory Design, and Anthropic’s Operational Tradeoffs",
        ],
    },
    {
        "case_id": "batch_001_c120",
        "label": "China signals Nvidia H200 approval",
        "titles": [
            "China signals approval for Nvidia H200 imports; tells Alibaba, Tencent and ByteDance to prepare orders",
            "China tells Alibaba, Tencent and ByteDance to prep Nvidia H200 orders, signaling near-approval",
            "China limits Nvidia H200 approvals to special cases, curbing Chinese access to top AI GPUs",
            "China drafting rules to cap Nvidia H200 purchases, forcing firms to justify needs",
        ],
    },
]
