"""Add platform column to content table

Revision ID: 5755b73ec0da
Revises: 6a13c2b1e1f8
Create Date: 2025-07-19 21:45:09.413571

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5755b73ec0da"
down_revision: str | None = "6a13c2b1e1f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contents", sa.Column("platform", sa.String(length=50), nullable=True))
    op.create_index(op.f("ix_contents_platform"), "contents", ["platform"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contents_platform"), table_name="contents")
    op.drop_column("contents", "platform")
    # ### end Alembic commands ###
