# mypy: ignore-errors
# ruff: noqa: B018, F821
"""Vulture whitelist for Newsly dynamic entrypoints and contracts.

This file is parsed by Vulture, not imported at runtime. Each expression marks a
name as used when the actual reference happens through framework registration,
serialization, ORM instrumentation, pytest, or another dynamic boundary.
"""

# Alembic hook metadata
upgrade
downgrade
target_metadata
revision
down_revision
branch_labels
depends_on

# Generated and TypedDict contracts
audio_urls  # unused variable (app/services/content_analyzer.py:86)
feed_confidence  # unused variable (app/services/onboarding.py:178)
platform_urls  # unused variable (app/services/content_analyzer.py:85)
rss_audio_url  # unused variable (app/services/content_analyzer.py:88)
rss_feeds  # unused variable (app/services/content_analyzer.py:87)
source_fields  # unused variable (app/services/llm_prompts.py:12)
source_guidelines  # unused variable (app/services/llm_prompts.py:13)

# Public constants and enum contracts
CLAIMED  # unused variable (app/models/contracts.py:207)
EXPIRED  # unused variable (app/models/contracts.py:208)
OPENED  # unused variable (app/models/contracts.py:130)
PODCAST_RSS  # unused variable (app/models/contracts.py:174)
SUBSTACK  # unused variable (app/models/contracts.py:173)
SUMMARY  # unused variable (app/models/contracts.py:215)
V1  # unused variable (app/models/contracts.py:97)

# Pydantic and settings fields
access_token_expire_minutes  # unused variable (app/core/settings.py:100)
admin_password_configured  # unused variable (app/core/settings.py:106)
anthropic_api_key_configured  # unused variable (app/core/settings.py:134)
archetype  # unused variable (app/models/metadata/summaries.py:391)
architecture  # unused variable (app/models/metadata/summaries.py:337)
artifact_mode  # unused variable (app/models/api/share_actions.py:117)
background  # unused variable (app/models/metadata/longform_artifacts.py:78)
best_fit_use_cases  # unused variable (app/models/metadata/summaries.py:341)
caveats  # unused variable (app/models/metadata/summaries.py:317)
cerebras_api_key_configured  # unused variable (app/core/settings.py:144)
channel_name  # unused variable (app/models/metadata/podcasts.py:49)
llm_task_sandbox_e2b_api_key_configured  # unused variable (app/core/settings.py:155)
compact_text  # unused variable (app/models/api/content_discussions.py:38)
completed_count  # unused variable (app/models/api/scraper_configs.py:15)
content_body_storage_access_key_configured  # unused variable (app/core/settings.py:121)
content_body_storage_bucket_configured  # unused variable (app/core/settings.py:118)
content_body_storage_endpoint_configured  # unused variable (app/core/settings.py:119)
content_body_storage_secret_key_configured  # unused variable (app/core/settings.py:122)
counterpoint  # unused variable (app/models/metadata/longform_artifacts.py:64)
current_focus  # unused variable (app/models/metadata/longform_artifacts.py:79)
discovery_time  # unused variable (app/models/metadata/news.py:104)
decks  # unused variable (app/models/api/learning_decks.py:74)
estimated_duration_seconds  # unused variable (app/services/audio_episodes.py:72)
exa_api_key_configured  # unused variable (app/core/settings.py:145)
extracted_at  # unused variable (app/models/metadata/source.py:73)
exa_results_per_query  # unused variable (app/models/api/onboarding.py:96)
favorite_ids  # unused variable (app/models/llm/feed_discovery.py:13)
feedback_id  # unused variable (app/models/api/feedback.py:58)
filters_hash  # unused variable (app/models/api/pagination.py:13)
final_url_after_redirects  # unused variable (app/models/metadata/articles.py:60)
firecrawl_api_key_configured  # unused variable (app/core/settings.py:153)
generated_by_model  # unused variable (app/models/metadata/insight_reports.py:75)
google_api_key_configured  # unused variable (app/core/settings.py:135)
google_cloud_project_configured  # unused variable (app/core/settings.py:136)
group_label  # unused variable (app/models/api/content_discussions.py:27)
has_transcript  # unused variable (app/models/metadata/podcasts.py:53)
has_x_bookmark_sync  # unused variable (app/models/api/users.py:37)
http_max_retries  # unused variable (app/core/settings.py:392)
hypothesis  # unused variable (app/models/metadata/summaries.py:325)
implications  # unused variable (app/models/metadata/summaries.py:308)
instruction_prompt  # unused variable (app/models/domain/user_profile.py:33)
interfaces  # unused variable (app/models/metadata/summaries.py:338)
internal_links  # unused variable (app/models/domain/content.py:39)
is_default  # unused variable (app/models/api/onboarding.py:129)
jwt_algorithm  # unused variable (app/core/settings.py:99)
jwt_secret_configured  # unused variable (app/core/settings.py:105)
journal_ref  # unused variable (app/models/metadata/source.py:71)
key_actors  # unused variable (app/models/metadata/longform_artifacts.py:94)
key_takeaway  # unused variable (app/models/api/content.py:102)
latest_publication_at  # unused variable (app/models/api/scraper_configs.py:19)
learning_sandbox_e2b_api_key_configured  # unused variable (app/core/settings.py:158)
limitations  # unused variable (app/models/metadata/summaries.py:328)
limits  # unused variable (app/models/metadata/longform_artifacts.py:107)
linked_context  # unused variable (app/models/metadata/summaries.py:318)
listen_notes_api_key_configured  # unused variable (app/core/settings.py:148)
LONG  # unused variable (app/models/api/content_actions.py:152)
longform_artifact  # unused variable (app/models/api/content.py:319)
longform_status  # unused variable (app/models/api/onboarding.py:196)
maturity_signals  # unused variable (app/models/metadata/summaries.py:340)
max_content_length  # unused variable (app/core/settings.py:261)
methods  # unused variable (app/models/metadata/summaries.py:326)
model_config  # unused variable (app/core/settings.py:222)
notable_arguments  # unused variable (app/models/metadata/summaries.py:297)
notable_links  # unused variable (app/models/metadata/summaries.py:714)
openai_api_key_configured  # unused variable (app/core/settings.py:132)
openrouter_api_key_configured  # unused variable (app/core/settings.py:133)
original_content_id  # unused variable (app/models/api/content_actions.py:107)
page_size  # unused variable (app/models/api/pagination.py:23)
podcast_index_api_key_configured  # unused variable (app/core/settings.py:151)
podcast_index_api_secret_configured  # unused variable (app/core/settings.py:152)
poll_interval_seconds  # unused variable (app/models/api/cli.py:35)
practical_takeaways  # unused variable (app/models/metadata/summaries.py:298)
preferences  # unused variable (app/models/api/agent.py:84)
prereqs  # unused variable (app/models/metadata/longform_artifacts.py:100)
primary_claim  # unused variable (app/models/metadata/summaries.py:315)
refresh_token_expire_days  # unused variable (app/core/settings.py:101)
representative_comments  # unused variable (app/models/metadata/summaries.py:719)
requested_count  # unused variable (app/models/api/content_actions.py:36)
read_on_play_content_ids  # unused variable (app/models/api/audio_episodes.py:51)
read_on_play_news_item_ids  # unused variable (app/models/api/audio_episodes.py:52)
run_created_at  # unused variable (app/models/api/discovery.py:44)
runware_api_key_configured  # unused variable (app/core/settings.py:143)
seed_feeds  # unused variable (app/models/api/agent.py:86)
seed_urls  # unused variable (app/models/api/agent.py:85)
setup_constraints  # unused variable (app/models/metadata/summaries.py:339)
SHORT  # unused variable (app/models/api/content_actions.py:150)
situation  # unused variable (app/models/metadata/longform_artifacts.py:73)
schema_version  # unused variable (app/models/metadata/source.py:57)
share_audio_url  # unused variable (app/models/api/audio_episodes.py:67)
share_page_url  # unused variable (app/models/api/audio_episodes.py:66)
source_context  # unused variable (app/models/metadata/longform_artifacts.py:229)
source_notes_available  # unused variable (app/models/api/learning_decks.py:64)
source_titles  # unused variable (app/models/api/audio_episodes.py:50)
sources_used  # unused variable (app/models/api/share_actions.py:146)
speakers  # unused variable (app/models/metadata/summaries.py:296)
spotify_client_id_configured  # unused variable (app/core/settings.py:149)
spotify_client_secret_configured  # unused variable (app/core/settings.py:150)
stake  # unused variable (app/models/metadata/longform_artifacts.py:89)
stance  # unused variable (app/models/metadata/summaries.py:668)
summarization_date  # unused variable (app/models/metadata/summaries.py:129)
summary_type  # unused variable (app/models/metadata/summaries.py:109)
SYSTEM  # unused variable (app/models/api/chat.py:22)
thesis  # unused variable (app/models/metadata/longform_artifacts.py:63)
time_or_cost  # unused variable (app/models/metadata/longform_artifacts.py:101)
timeline  # unused variable (app/models/metadata/longform_artifacts.py:93)
total_requested  # unused variable (app/models/api/content_actions.py:78)
unread_count  # unused variable (app/models/api/content_actions.py:99)
user_status  # unused variable (app/models/api/content.py:69)
video_audio_path  # unused variable (app/models/metadata/news.py:53)
video_url  # unused variable (app/models/metadata/podcasts.py:47)
viewer_available  # unused variable (app/models/api/learning_decks.py:63)
what  # unused variable (app/models/metadata/longform_artifacts.py:84)
what_it_explains  # unused variable (app/models/metadata/longform_artifacts.py:68)
what_to_watch  # unused variable (app/models/metadata/longform_artifacts.py:95)
what_youll_make  # unused variable (app/models/metadata/longform_artifacts.py:99)
when  # unused variable (app/models/metadata/longform_artifacts.py:83)
when_to_use_it  # unused variable (app/models/metadata/longform_artifacts.py:69)
x_app_bearer_token_configured  # unused variable (app/core/settings.py:186)
x_client_id_configured  # unused variable (app/core/settings.py:187)
x_client_secret_configured  # unused variable (app/core/settings.py:188)
x_token_encryption_key_configured  # unused variable (app/core/settings.py:192)

# Pytest and mock conventions
_.side_effect  # unused attribute (tests/pipeline/test_content_worker.py:357)
pytestmark  # unused variable (tests/routers/api/test_content_detail_subscribe.py:9)

# Runtime framework attributes
_.namer  # unused attribute (app/core/logging.py:420)
_.row_factory  # unused attribute (scripts/export_title_clustering_dataset.py:67)

# SQLAlchemy ORM fields
_.approved_at  # unused attribute (app/services/cli_link.py:168)
_.approved_by_user_id  # unused attribute (app/services/cli_link.py:164)
_.byte_size  # unused attribute (app/services/content_bodies.py:303)
_.claimed_at  # unused attribute (app/services/cli_link.py:207)
_.comment_sort  # unused attribute (app/services/discussion_fetcher.py:467)
_.last_synced_item_id  # unused attribute (app/services/x_integration.py:428)
_.storage_bucket  # unused attribute (app/services/content_bodies.py:299)
_.storage_provider  # unused attribute (app/services/content_bodies.py:298)
_.summary_model  # unused attribute (app/services/news_item_discussions.py:913)
approved_at  # unused variable (app/models/db/cli.py:34)
approved_by_user_id  # unused variable (app/models/db/cli.py:30)
byte_size  # unused variable (app/models/db/content.py:114)
claimed_at  # unused variable (app/models/db/cli.py:35)
council_persona_prompt  # unused variable (app/models/db/chat.py:40)
first_synced_at  # unused variable (app/models/db/integrations.py:81)
lane_summary  # unused variable (app/models/db/onboarding.py:31)
last_synced_item_id  # unused variable (app/models/db/integrations.py:56)
storage_bucket  # unused variable (app/models/db/content.py:110)
storage_provider  # unused variable (app/models/db/content.py:109)
prompt_version  # unused variable (app/models/db/audio_episode.py:26)
summary_model  # unused variable (app/models/db/news.py:139)
usage_json  # unused variable (app/models/db/llm_tasks.py:54)
