"""Pure-ish query and suggestion heuristics for onboarding discovery."""

from app.services.onboarding import (
    _build_discovery_queries,
    _build_profile_queries,
    _clean_queries,
    _dedupe_suggestions,
    _discovery_context_hint,
    _enforce_query_word_range,
    _extract_subreddit,
    _merge_topics,
    _normalize_lane_target,
    _normalize_score,
    _normalize_selected_suggestion_type,
    _normalize_suggestion_type,
    _normalize_suggestions,
    _query_focus_phrase,
    _query_patterns_for_target,
    _refine_lane_queries,
    _select_prompt_results,
    _suggestion_key,
    _suggestion_label,
    _target_query_keyword,
)

__all__ = [
    "_build_discovery_queries",
    "_build_profile_queries",
    "_clean_queries",
    "_dedupe_suggestions",
    "_discovery_context_hint",
    "_enforce_query_word_range",
    "_extract_subreddit",
    "_merge_topics",
    "_normalize_lane_target",
    "_normalize_score",
    "_normalize_selected_suggestion_type",
    "_normalize_suggestion_type",
    "_normalize_suggestions",
    "_query_focus_phrase",
    "_query_patterns_for_target",
    "_refine_lane_queries",
    "_select_prompt_results",
    "_suggestion_key",
    "_suggestion_label",
    "_target_query_keyword",
]
