"""Emit Go CLI contract artifacts from the reviewed registry."""

from __future__ import annotations

from enum import IntEnum

from app.models.contracts_registry import (
    CONTRACT_ENUMS,
    CONTRACT_MODELS,
    CONTRACT_UNTYPED_FIELD_ALLOWLIST,
    EnumSpec,
    ModelSpec,
    Target,
)
from scripts.contracts_codegen.introspect import (
    ContractTypeResolver,
    FieldIR,
    TypeIR,
    introspect_models,
    validate_contract_models,
)

HEADER = """// Code generated by scripts/generate_go_contracts.py. Do not edit.

package api
"""

_INITIALISMS = {
    "api": "API",
    "html": "HTML",
    "http": "HTTP",
    "id": "ID",
    "ids": "IDs",
    "ios": "IOS",
    "json": "JSON",
    "llm": "LLM",
    "qr": "QR",
    "rss": "RSS",
    "sha": "SHA",
    "sha256": "SHA256",
    "ui": "UI",
    "url": "URL",
    "urls": "URLs",
    "utc": "UTC",
}


def build_go_contracts(
    model_specs: list[ModelSpec] | None = None,
    enum_specs: list[EnumSpec] | None = None,
) -> str:
    """Build the generated Go CLI model and enum source."""
    specs = CONTRACT_MODELS if model_specs is None else model_specs
    enums = CONTRACT_ENUMS if enum_specs is None else enum_specs
    validate_contract_models(
        specs,
        enums,
        untyped_field_allowlist=CONTRACT_UNTYPED_FIELD_ALLOWLIST,
    )
    context = _GoTypeContext()
    resolver = ContractTypeResolver.from_specs(
        specs,
        enums,
        target=Target.CLI,
        untyped_field_allowlist=CONTRACT_UNTYPED_FIELD_ALLOWLIST,
    )

    enum_sections = [
        _go_enum(context.enum_name(spec), spec) for spec in enums if spec.targets & Target.CLI
    ]

    cli_specs = [spec for spec in specs if spec.targets & Target.CLI]
    model_irs = introspect_models([spec.model for spec in cli_specs], resolver=resolver)
    model_sections = [
        _go_model_struct(context.model_name(spec), model_ir.fields, context)
        for spec, model_ir in zip(cli_specs, model_irs, strict=True)
    ]

    sections = [HEADER.rstrip()]
    if context.imports:
        sections.append(_go_imports(context.imports))
    sections.extend(enum_sections)
    sections.extend(model_sections)
    return "\n\n".join(section for section in sections if section).rstrip() + "\n"


class _GoTypeContext:
    def __init__(self) -> None:
        self.imports: set[str] = set()

    def model_name(self, spec: ModelSpec) -> str:
        return spec.go_name or _strip_dto_suffix(spec.model.__name__)

    def enum_name(self, spec: EnumSpec) -> str:
        return spec.go_name or spec.enum.__name__

    def go_type(self, type_ir: TypeIR, *, optional: bool) -> str:
        go_type = self._go_non_optional_type(type_ir)
        if (type_ir.optional or optional) and _uses_pointer_for_optional(type_ir):
            return f"*{go_type}"
        return go_type

    def _go_non_optional_type(self, type_ir: TypeIR) -> str:
        if type_ir.kind == "datetime":
            self.imports.add("time")
            return "time.Time"

        if type_ir.kind == "scalar":
            if type_ir.scalar == "string":
                return "string"
            if type_ir.scalar == "int":
                return "int"
            if type_ir.scalar == "float":
                return "float64"
            if type_ir.scalar == "bool":
                return "bool"

        if type_ir.kind == "untyped":
            raise ValueError("Any is only supported inside allowlisted dict[str, Any]")

        if type_ir.kind in {"enum", "model"} and type_ir.name is not None:
            return type_ir.name
        if type_ir.kind == "list" and type_ir.item_type is not None:
            return f"[]{self.go_type(type_ir.item_type, optional=False)}"
        if type_ir.kind == "dict" and type_ir.value_type is not None:
            if type_ir.value_type.kind == "untyped":
                self.imports.add("encoding/json")
                return "json.RawMessage"
            return f"map[string]{self.go_type(type_ir.value_type, optional=False)}"

        raise ValueError(f"Unsupported Go TypeIR: {type_ir!r}")


def _go_imports(imports: set[str]) -> str:
    lines = ["import ("]
    for import_name in sorted(imports):
        lines.append(f'\t"{import_name}"')
    lines.append(")")
    return "\n".join(lines)


def _go_enum(name: str, spec: EnumSpec) -> str:
    values = [item.value for item in spec.enum]
    if issubclass(spec.enum, IntEnum):
        return _go_int_enum(name, [int(value) for value in values])
    return _go_string_enum(name, [str(value) for value in values])


def _go_string_enum(name: str, values: list[str]) -> str:
    lines = [f"type {name} string", "", "const ("]
    for value in values:
        lines.append(f'\t{name}{_go_enum_suffix(value)} {name} = "{value}"')
    lines.append(")")
    lines.append("")
    lines.extend(_go_known_method(name, [_go_enum_suffix(value) for value in values]))
    return "\n".join(lines)


def _go_int_enum(name: str, values: list[int]) -> str:
    lines = [f"type {name} int", "", "const ("]
    for value in values:
        lines.append(f"\t{name}V{value} {name} = {value}")
    lines.append(")")
    lines.append("")
    lines.extend(_go_known_method(name, [f"V{value}" for value in values]))
    return "\n".join(lines)


def _go_known_method(name: str, suffixes: list[str]) -> list[str]:
    lines = [f"func (v {name}) Known() bool {{", "\tswitch v {"]
    if suffixes:
        cases = ", ".join(f"{name}{suffix}" for suffix in suffixes)
        lines.append(f"\tcase {cases}:")
        lines.append("\t\treturn true")
    lines.append("\tdefault:")
    lines.append("\t\treturn false")
    lines.append("\t}")
    lines.append("}")
    return lines


def _go_model_struct(name: str, fields: tuple[FieldIR, ...], context: _GoTypeContext) -> str:
    go_fields = [
        _GoField(
            source=field,
            name=_go_field_name(field.python_name),
            wire_name=field.wire_name,
            type_name=context.go_type(field.type_ir, optional=not field.required),
        )
        for field in fields
    ]

    lines = [f"type {name} struct {{"]
    for field in go_fields:
        tag = field.json_tag
        lines.append(f"\t{field.name} {field.type_name} `{tag}`")
    lines.append("}")
    return "\n".join(lines)


class _GoField:
    def __init__(
        self,
        *,
        source: FieldIR,
        name: str,
        wire_name: str,
        type_name: str,
    ) -> None:
        self.source = source
        self.name = name
        self.wire_name = wire_name
        self.type_name = type_name

    @property
    def json_tag(self) -> str:
        tag = self.wire_name
        if not self.source.required:
            tag += ",omitempty"
        return f'json:"{tag}"'


def _uses_pointer_for_optional(type_ir: TypeIR) -> bool:
    return type_ir.kind not in {"list", "dict"}


def _strip_dto_suffix(name: str) -> str:
    return name.removesuffix("Dto")


def _go_field_name(name: str) -> str:
    return "".join(_go_identifier_part(part) for part in name.split("_"))


def _go_enum_suffix(value: str) -> str:
    suffix = "".join(
        _go_identifier_part(part) for part in value.replace("-", "_").split("_") if part
    )
    if suffix[:1].isdigit():
        return f"V{suffix}"
    return suffix


def _go_identifier_part(part: str) -> str:
    lowered = part.lower()
    if lowered in _INITIALISMS:
        return _INITIALISMS[lowered]
    if not part:
        return ""
    if part[0].isdigit():
        return part
    return part[:1].upper() + part[1:].lower()
