"""Emit Swift contract artifacts from the reviewed registry."""

from __future__ import annotations

import json
from enum import Enum, IntEnum

from app.models.contracts_registry import (
    CONTRACT_ENUMS,
    CONTRACT_MODELS,
    CONTRACT_UNTYPED_FIELD_ALLOWLIST,
    EnumSpec,
    ModelSpec,
    Target,
)
from scripts.contracts_codegen.introspect import (
    ContractTypeResolver,
    FieldIR,
    TypeIR,
    introspect_models,
    validate_contract_models,
)
from scripts.contracts_codegen.policy import is_lenient_policy

HEADER = """// swiftlint:disable all
// Generated by scripts/generate_ios_contracts.py. Do not edit manually.
import Foundation

"""


def build_swift_contracts(enum_specs: list[EnumSpec] | None = None) -> str:
    """Build the generated Swift enum source."""
    validate_contract_models(
        CONTRACT_MODELS,
        CONTRACT_ENUMS,
        untyped_field_allowlist=CONTRACT_UNTYPED_FIELD_ALLOWLIST,
    )
    specs = CONTRACT_ENUMS if enum_specs is None else enum_specs
    sections = [HEADER]
    for spec in specs:
        if not spec.targets & Target.IOS:
            continue
        swift_name = spec.swift_name or f"API{spec.enum.__name__}"
        if issubclass(spec.enum, IntEnum):
            if spec.open:
                raise ValueError(f"Open IntEnum is not supported for iOS: {spec.enum.__name__}")
            sections.append(_swift_int_enum(swift_name, [item.value for item in spec.enum]))
        else:
            sections.append(
                _swift_string_enum(
                    swift_name,
                    [str(item.value) for item in spec.enum],
                    open_enum=spec.open,
                )
            )
    return "\n".join(sections).rstrip() + "\n"


def build_swift_models(
    model_specs: list[ModelSpec] | None = None,
    enum_specs: list[EnumSpec] | None = None,
) -> str:
    """Build the generated Swift model source."""
    specs = CONTRACT_MODELS if model_specs is None else model_specs
    enums = CONTRACT_ENUMS if enum_specs is None else enum_specs
    validate_contract_models(
        specs,
        enums,
        untyped_field_allowlist=CONTRACT_UNTYPED_FIELD_ALLOWLIST,
    )
    context = _SwiftTypeContext()
    resolver = ContractTypeResolver.from_specs(
        specs,
        enums,
        target=Target.IOS,
        untyped_field_allowlist=CONTRACT_UNTYPED_FIELD_ALLOWLIST,
    )
    ios_specs = [spec for spec in specs if spec.targets & Target.IOS]
    model_irs = introspect_models([spec.model for spec in ios_specs], resolver=resolver)

    sections = [HEADER]
    for spec, model_ir in zip(ios_specs, model_irs, strict=True):
        sections.append(_swift_model_struct(context.model_name(spec), model_ir.fields, context))
    return "\n".join(sections).rstrip() + "\n"


def _swift_string_enum(
    name: str,
    values: list[str],
    *,
    codable: bool = True,
    open_enum: bool = False,
) -> str:
    if open_enum:
        return _swift_open_string_enum(name, values)

    protocols = ["String"]
    if codable:
        protocols.extend(["Codable", "CaseIterable"])
    protocol_list = ", ".join(protocols)
    lines = [f"enum {name}: {protocol_list} {{"]
    for value in values:
        case_name = value.replace("-", "_")
        lines.append(f'    case {case_name} = "{value}"')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _swift_open_string_enum(name: str, values: list[str]) -> str:
    unknown_case_name = "unknownRaw" if "unknown" in values else "unknown"
    lines = [f"enum {name}: Codable, Equatable, Hashable {{"]
    for value in values:
        lines.append(f"    case {_swift_case_name(value)}")
    lines.append(f"    case {unknown_case_name}(String)")
    lines.append("")
    lines.append(f"    static let knownCases: [{name}] = [")
    for value in values:
        lines.append(f"        .{_swift_case_name(value)},")
    lines.append("    ]")
    lines.append("")
    lines.append("    var rawValue: String {")
    lines.append("        switch self {")
    for value in values:
        lines.append(f'        case .{_swift_case_name(value)}: "{value}"')
    lines.append(f"        case .{unknown_case_name}(let rawValue): rawValue")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    init(rawValue: String) {")
    lines.append("        switch rawValue {")
    for value in values:
        lines.append(f'        case "{value}": self = .{_swift_case_name(value)}')
    lines.append(f"        default: self = .{unknown_case_name}(rawValue)")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    init(from decoder: Decoder) throws {")
    lines.append("        let container = try decoder.singleValueContainer()")
    lines.append("        self.init(rawValue: try container.decode(String.self))")
    lines.append("    }")
    lines.append("")
    lines.append("    func encode(to encoder: Encoder) throws {")
    lines.append("        var container = encoder.singleValueContainer()")
    lines.append("        try container.encode(rawValue)")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _swift_int_enum(name: str, values: list[int]) -> str:
    lines = [f"enum {name}: Int, Codable, CaseIterable {{"]
    for value in values:
        lines.append(f"    case v{value} = {value}")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _swift_case_name(value: str) -> str:
    return value.replace("-", "_")


class _SwiftTypeContext:
    def model_name(self, spec: ModelSpec) -> str:
        return spec.swift_name or f"API{_strip_dto_suffix(spec.model.__name__)}"

    def swift_type(self, type_ir: TypeIR) -> tuple[str, str, bool]:
        swift_type = self._swift_non_optional_type(type_ir)
        if type_ir.optional:
            return f"{swift_type}?", swift_type, True
        return swift_type, swift_type, False

    def _swift_non_optional_type(self, type_ir: TypeIR) -> str:
        if type_ir.kind == "datetime":
            return "String"
        if type_ir.kind == "scalar":
            if type_ir.scalar == "string":
                return "String"
            if type_ir.scalar == "int":
                return "Int"
            if type_ir.scalar == "float":
                return "Double"
            if type_ir.scalar == "bool":
                return "Bool"
        if type_ir.kind == "untyped":
            return "AnyCodable"
        if type_ir.kind in {"enum", "model"} and type_ir.name is not None:
            return type_ir.name
        if type_ir.kind == "list" and type_ir.item_type is not None:
            return f"[{self.swift_type(type_ir.item_type)[0]}]"
        if type_ir.kind == "dict" and type_ir.value_type is not None:
            return f"[String: {self.swift_type(type_ir.value_type)[0]}]"

        raise ValueError(f"Unsupported Swift TypeIR: {type_ir!r}")


def _swift_model_struct(name: str, fields: tuple[FieldIR, ...], context: _SwiftTypeContext) -> str:
    typed_fields = [
        _SwiftField(
            source=field,
            name=_swift_identifier(_snake_to_lower_camel(field.python_name)),
            wire_name=field.wire_name,
            type_name=context.swift_type(field.type_ir)[0],
            decode_type=context.swift_type(field.type_ir)[1],
            optional=context.swift_type(field.type_ir)[2],
        )
        for field in fields
    ]

    lines = [f"struct {name}: Codable {{"]
    for field in typed_fields:
        lines.append(f"    let {field.name}: {field.type_name}")
    lines.append("")
    lines.extend(_swift_memberwise_init(typed_fields))
    lines.append("")
    lines.append("    enum CodingKeys: String, CodingKey {")
    for field in typed_fields:
        lines.append(f'        case {field.name} = "{field.wire_name}"')
    lines.append("    }")
    lines.append("")
    lines.extend(_swift_decoder_init(typed_fields))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


class _SwiftField:
    def __init__(
        self,
        *,
        source: FieldIR,
        name: str,
        wire_name: str,
        type_name: str,
        decode_type: str,
        optional: bool,
    ) -> None:
        self.source = source
        self.name = name
        self.wire_name = wire_name
        self.type_name = type_name
        self.decode_type = decode_type
        self.optional = optional

    @property
    def is_lenient(self) -> bool:
        return is_lenient_policy(self.source.contract_policy)

    @property
    def default_expr(self) -> str | None:
        if self.optional:
            return "nil"
        if self.source.default_factory in {"list", "set"}:
            return "[]"
        if self.source.default_factory == "dict":
            return "[:]"
        default = self.source.default
        if default is None:
            return None
        if isinstance(default, Enum):
            return f".{_swift_case_name(str(default.value))}"
        if isinstance(default, bool):
            return "true" if default else "false"
        if isinstance(default, int | float):
            return str(default)
        if isinstance(default, str):
            if self.decode_type != "String":
                return f".{_swift_case_name(default)}"
            return json.dumps(default)
        if default == []:
            return "[]"
        if default == {}:
            return "[:]"
        return None


def _swift_memberwise_init(fields: list[_SwiftField]) -> list[str]:
    lines = ["    init("]
    for index, field in enumerate(fields):
        separator = "," if index < len(fields) - 1 else ""
        default = field.default_expr
        default_suffix = f" = {default}" if default is not None else ""
        lines.append(f"        {field.name}: {field.type_name}{default_suffix}{separator}")
    lines.append("    ) {")
    for field in fields:
        lines.append(f"        self.{field.name} = {field.name}")
    lines.append("    }")
    return lines


def _swift_decoder_init(fields: list[_SwiftField]) -> list[str]:
    lines = [
        "    init(from decoder: Decoder) throws {",
        "        let container = try decoder.container(keyedBy: CodingKeys.self)",
    ]
    for field in fields:
        if field.is_lenient:
            default_expr = field.default_expr
            if default_expr is None:
                raise ValueError(
                    f"{field.source.python_name}: lenient fields need a Swift default expression"
                )
            lines.append(
                f"        {field.name} = try container.decodeIfPresent("
                f"{field.decode_type}.self, forKey: .{field.name}) ?? {default_expr}"
            )
        elif field.optional:
            lines.append(
                f"        {field.name} = try container.decodeIfPresent("
                f"{field.decode_type}.self, forKey: .{field.name})"
            )
        else:
            lines.append(
                f"        {field.name} = try container.decode("
                f"{field.decode_type}.self, forKey: .{field.name})"
            )
    lines.append("    }")
    return lines


def _strip_dto_suffix(name: str) -> str:
    return name.removesuffix("Dto")


def _snake_to_lower_camel(name: str) -> str:
    parts = name.split("_")
    return parts[0] + "".join(part[:1].upper() + part[1:] for part in parts[1:])


_SWIFT_KEYWORDS = {
    "associatedtype",
    "class",
    "deinit",
    "enum",
    "extension",
    "fileprivate",
    "func",
    "import",
    "init",
    "inout",
    "internal",
    "let",
    "open",
    "operator",
    "private",
    "precedencegroup",
    "protocol",
    "public",
    "rethrows",
    "static",
    "struct",
    "subscript",
    "typealias",
    "var",
    "break",
    "case",
    "catch",
    "continue",
    "default",
    "defer",
    "do",
    "else",
    "fallthrough",
    "for",
    "guard",
    "if",
    "in",
    "repeat",
    "return",
    "throw",
    "switch",
    "where",
    "while",
}


def _swift_identifier(name: str) -> str:
    if name in _SWIFT_KEYWORDS:
        return f"`{name}`"
    return name
