use axum::extract::State;
use axum::http::StatusCode;
use axum::response::IntoResponse;
use axum::routing::get;
use axum::{Json, Router};
use newsly_contracts::{
    AccessTokenResponse, AdminLoginRequest, AdminLoginResponse, AgentLibraryDocumentResponse,
    AgentLibraryDocumentVariant, AgentLibraryFileResponse, AgentLibraryManifestResponse,
    AgentOnboardingCompleteRequest, AgentOnboardingStartRequest, AgentOnboardingStartResponse,
    AgentSearchRequest, AgentSearchResponse, AgentSearchResultKind, AgentSearchResultResponse,
    ApiKeyCreateResponse, ApiKeySummaryResponse, AppleSignInRequest, AssistantFeedOption,
    AssistantScreenContextDto, AssistantTurnRequest, AssistantTurnResponse, AudioEpisodeDelivery,
    AudioEpisodeKind, AudioEpisodeResponse, AudioEpisodeShareResponse, AudioEpisodeStatus,
    AudioTranscriptionHealthResponse, AudioTranscriptionResponse, BadgeStatsResponse,
    BriefingBlockDto, BriefingBlockType, BriefingDigSearchRequest, BriefingDigSearchResponse,
    BriefingDigSearchResult, BriefingDigSummarizeRequest, BriefingDigSummarizeResponse,
    BriefingDiscussionDto, BriefingFigureAlignment, BriefingFigurePlacement, BriefingFirstRunPhase,
    BriefingFirstRunProgress, BriefingFirstRunSourceOutcome, BriefingFirstRunSourceProgress,
    BriefingIndexResponse, BriefingLensResponse, BriefingLensSummary, BriefingNarrationRequest,
    BriefingNarrationResponse, BriefingParagraphDto, BriefingReadMarkRequest,
    BriefingReadMarkResponse, BriefingRefreshResponse, BriefingRunDto, BriefingRunKind,
    BriefingSegmentDto, BriefingSourceDto, BriefingTier, BulkMarkReadRequest, BulkMarkReadResponse,
    ChatGptUrlResponse, ChatMessageDisplayType, ChatMessageDto, ChatMessageRole,
    ChatSessionDetailDto, ChatSessionListResponse, ChatSessionSummaryDto, ChatToolProgressDto,
    CliLinkApproveRequest, CliLinkApproveResponse, CliLinkPollResponse, CliLinkStartRequest,
    CliLinkStartResponse, CliLinkStatus, ContentBodyResponse, ContentClassification,
    ContentDetailResponse, ContentDiscussionResponse, ContentInteractionType, ContentListResponse,
    ContentStatus, ContentSubmissionResponse, ContentSummaryBulletPoint, ContentSummaryQuote,
    ContentSummaryResponse, ContentType, CouncilCandidate, CouncilPersonaConfig,
    CouncilPersonaInput, CouncilRetryRequest, CouncilSelectRequest, CouncilStartRequest,
    CreateChatSessionRequest, CreateChatSessionResponse, CreateUserScraperConfig,
    CustomNarrationCreateRequest, DebugUserSessionRequest, DeleteAccountRequest,
    DeleteAccountResponse, DeleteStatus, DeleteUserLlmIntegrationResponse, DetectedFeed,
    DiscussionCommentResponse, DiscussionGroupResponse, DiscussionItemResponse,
    DiscussionLinkResponse, DiscussionMode, DiscussionSummaryCommentResponse,
    DiscussionSummaryLinkResponse, DiscussionSummaryResponse, DiscussionSummaryTopicResponse,
    ErrorEnvelope, FeedFormat, FeedSubscriptionOutcome, FeedType, HealthChecks, HealthResponse,
    HealthStatus, IntegrationDisconnectResponse, IntegrationDisconnectStatus, JobStatusResponse,
    KnowledgeMutationResponse, KnowledgeMutationStatus, LearningDeckCreateRequest,
    LearningDeckListResponse, LearningDeckResponse, LearningDeckRunResponse, LearningDeckRunStatus,
    LearningDeckShareResponse, LearningDeckSourceKind, LearningDeckStatus,
    LearningDeckTimelineEntry, LearningDeckUrlResponse, LlmProvider, LlmTaskActionListResponse,
    LlmTaskActionRejectRequest, LlmTaskActionResponse, LlmTaskActionStatus, LlmTaskApprovalPolicy,
    LlmTaskMode, LlmTaskStatus, LongFormStatsResponse, MarkReadResponse, MarkUnreadResponse,
    MessageProcessingStatus, MessageStatusResponse, NewsItemDetailResponse, NewsItemListResponse,
    NewsItemStatus, NewsItemSummaryResponse, NewsItemVisibilityScope,
    OnboardingAudioDiscoverRequest, OnboardingAudioDiscoverResponse, OnboardingAudioLanePreview,
    OnboardingAudioLanePreviewResponse, OnboardingAudioLaneTarget, OnboardingCompleteRequest,
    OnboardingCompleteResponse, OnboardingDiscoveryLaneStatus, OnboardingDiscoveryStatusResponse,
    OnboardingFastDiscoverRequest, OnboardingFastDiscoverResponse, OnboardingProfileRequest,
    OnboardingProfileResponse, OnboardingSelectedAggregator, OnboardingSuggestion,
    OnboardingSuggestionType, OnboardingTutorialResponse, OnboardingVoiceParseRequest,
    OnboardingVoiceParseResponse, OperationStatus, PaginationMetadata, ProcessingCountResponse,
    ReadingExperience, RecordContentInteractionRequest, RecordContentInteractionResponse,
    RefreshTokenRequest, SavedSource, ScraperConfigResponse, ScraperConfigStatsResponse,
    ScraperType, SendChatMessageRequest, SendMessageResponse, ShareActionCreateRequest,
    ShareActionResponse, SubmitContentRequest, SubmitFeedbackRequest, SubmitFeedbackResponse,
    SubscribeToFeedRequest, SummaryKind, SummaryVersion, TaskStatus, TaskType, TokenResponse,
    UnreadCountsResponse, UpdateChatSessionRequest, UpdateUserProfileRequest,
    UpdateUserScraperConfig, UpsertUserLlmIntegrationRequest, UserLlmIntegrationResponse,
    UserLlmIntegrationTestResponse, UserLlmProvider, UserResponse, XConnectionResponse,
    XOAuthExchangeRequest, XOAuthStartRequest, XOAuthStartResponse,
};
use newsly_contracts::{
    ConvertNewsItemResponse, ConvertNewsResponse, DownloadMoreRequest, DownloadMoreResponse,
    MixedSearchFeedResultResponse, MixedSearchResponse, NarrationResponse, NarrationTargetType,
    PodcastEpisodeSearchResponse, PodcastEpisodeSearchResultResponse, SubmissionContentResult,
    SubmissionFeedInitialDownloadResponse, SubmissionFeedSubscriptionResponse,
    SubmissionFeedSubscriptionResult, SubmissionKind, SubmissionLearningDeckResult,
    SubmissionNoActionResult, SubmissionOutcome, SubmissionResult, SubmissionStatusListResponse,
    SubmissionStatusResponse, TweetLength, TweetSuggestion, TweetSuggestionsRequest,
    TweetSuggestionsResponse,
};
use utoipa::openapi::security::{Http, HttpAuthScheme, SecurityScheme};
use utoipa::{Modify, OpenApi};

use crate::AppState;

pub(super) fn router() -> Router<AppState> {
    Router::new()
        .route("/health", get(compatibility_health))
        .route("/health/live", get(liveness))
        .route("/health/ready", get(readiness))
        .route("/openapi.json", get(openapi))
}

#[utoipa::path(
    get,
    path = "/health/live",
    tag = "operations",
    responses((status = 200, description = "Process is alive", body = HealthResponse))
)]
async fn liveness(State(state): State<AppState>) -> Json<HealthResponse> {
    Json(HealthResponse::live(state.service_name.as_ref()))
}

#[utoipa::path(
    get,
    path = "/health/ready",
    tag = "operations",
    responses(
        (status = 200, description = "Process and database are ready", body = HealthResponse),
        (status = 503, description = "Database is unavailable", body = HealthResponse)
    )
)]
async fn readiness(State(state): State<AppState>) -> impl IntoResponse {
    check_readiness(&state).await
}

#[utoipa::path(
    get,
    path = "/health",
    operation_id = "healthCheck",
    tag = "operations",
    responses(
        (status = 200, description = "Compatibility readiness endpoint", body = HealthResponse),
        (status = 503, description = "Database is unavailable", body = HealthResponse)
    )
)]
async fn compatibility_health(State(state): State<AppState>) -> impl IntoResponse {
    check_readiness(&state).await
}

async fn check_readiness(state: &AppState) -> (StatusCode, Json<HealthResponse>) {
    match tokio::time::timeout(state.readiness_timeout, state.database.check()).await {
        Ok(Ok(())) => (
            StatusCode::OK,
            Json(HealthResponse::ready(state.service_name.as_ref())),
        ),
        Ok(Err(error)) => {
            tracing::warn!(error = %error, "PostgreSQL readiness check failed");
            (
                StatusCode::SERVICE_UNAVAILABLE,
                Json(HealthResponse::database_unavailable(
                    state.service_name.as_ref(),
                )),
            )
        }
        Err(_) => {
            tracing::warn!(
                timeout_ms = state.readiness_timeout.as_millis(),
                "PostgreSQL readiness check timed out"
            );
            (
                StatusCode::SERVICE_UNAVAILABLE,
                Json(HealthResponse::database_unavailable(
                    state.service_name.as_ref(),
                )),
            )
        }
    }
}

#[derive(OpenApi)]
#[openapi(
    info(title = "Newsly Rust API", version = "0.1.0"),
    paths(
        liveness,
        readiness,
        compatibility_health,
        crate::briefing::get_index,
        crate::briefing::get_lens,
        crate::briefing::mark_read,
        crate::briefing::mark_lens_read,
        crate::briefing::refresh,
        crate::briefing::dig_search,
        crate::briefing::dig_summarize,
        crate::briefing::legacy_narration,
        crate::briefing::chaptered_narration,
        crate::briefing::narration_status,
        crate::agent::search_agent,
        crate::agent::get_agent_library_manifest,
        crate::agent::get_agent_library_file,
        crate::admin_evals::page,
        crate::admin_evals::run,
        crate::chat::list_sessions,
        crate::chat::list_sessions_page,
        crate::chat::create_session,
        crate::chat::get_session,
        crate::chat::update_session,
        crate::chat::delete_session,
        crate::chat::send_message,
        crate::chat::create_assistant_turn,
        crate::chat::get_message_status,
        crate::chat::council::start_council_mode,
        crate::chat::council::select_council_mode_branch,
        crate::chat::council::retry_council_mode_branch,
        crate::audio_episodes::create_fast_news_audio_episode,
        crate::audio_episodes::create_content_council_audio_episode,
        crate::audio_episodes::create_news_item_discussion_audio_episode,
        crate::audio_episodes::create_custom_narration_audio_episode,
        crate::audio_episodes::list_custom_narration_audio_episodes,
        crate::audio_episodes::get_audio_episode,
        crate::audio_episodes::get_audio_episode_audio,
        crate::audio_episodes::finish_audio_episode_playback,
        crate::audio_episodes::enable_audio_episode_public_share,
        crate::audio_episodes::disable_audio_episode_public_share,
        crate::audio_episodes::stream_audio_episode,
        crate::content_bodies::get_content_body,
        crate::content_bodies::get_content_chat_url,
        crate::content_bodies::get_news_item_body,
        crate::content_feeds::list_contents,
        crate::content_feeds::get_recently_read,
        crate::content_feeds::get_knowledge_library,
        crate::content_feeds::search_contents,
        crate::content_misc::convert_content_news_to_article,
        crate::content_misc::convert_news_item_to_article,
        crate::content_misc::download_more_from_series,
        crate::content_misc::get_narration,
        crate::content_misc::get_tweet_suggestions,
        crate::content_misc::list_submission_statuses,
        crate::content_misc::refresh_content_discussion,
        crate::content_misc::refresh_news_item_discussion,
        crate::content_misc::search_podcast_episode_matches,
        crate::content_misc::search_mixed_contents,
        crate::content_read::get_content_detail,
        crate::content_read::get_news_item,
        crate::content_read::list_news_items,
        crate::discussions::get_content_discussion,
        crate::discussions::get_news_item_discussion,
        crate::jobs::get_job,
        crate::learning_decks::operations::list_decks,
        crate::learning_decks::operations::create_deck,
        crate::learning_decks::operations::get_deck,
        crate::learning_decks::operations::retry_deck,
        crate::learning_decks::operations::delete_deck,
        crate::learning_decks::operations::enable_share,
        crate::learning_decks::operations::disable_share,
        crate::learning_decks::operations::create_viewer_url,
        crate::learning_decks::operations::create_source_notes_url,
        crate::integrations::get_llm_integrations,
        crate::integrations::put_llm_integration,
        crate::integrations::delete_llm_integration_endpoint,
        crate::integrations::test_llm_integration,
        crate::integrations::get_x_connection,
        crate::integrations::start_x_oauth_flow,
        crate::integrations::exchange_x_oauth_code,
        crate::integrations::disconnect_x_connection,
        crate::llm_tasks::list_task_actions,
        crate::share_actions::approve_share_action_callback,
        crate::llm_tasks::reject_task_action,
        crate::share_actions::create_share_action,
        crate::share_actions::get_share_action,
        crate::openai::transcription_health,
        crate::openai::transcribe_audio,
        crate::mutations::create_feedback,
        crate::mutations::record_content_interaction,
        crate::content_actions::mark_content_read,
        crate::content_actions::mark_content_unread,
        crate::content_actions::bulk_mark_read,
        crate::content_actions::save_to_knowledge,
        crate::content_actions::remove_from_knowledge,
        crate::content_submission::submit_content,
        crate::news_actions::mark_news_items_read,
        crate::onboarding::discovery_status,
        crate::onboarding::tutorial_complete,
        crate::onboarding_flow::build_profile,
        crate::onboarding_flow::parse_voice,
        crate::onboarding_flow::fast_discover,
        crate::onboarding_flow::audio_discover,
        crate::onboarding_flow::complete_flow,
        crate::onboarding_flow::start_agent_onboarding,
        crate::onboarding_flow::get_agent_onboarding,
        crate::onboarding_flow::complete_agent_onboarding,
        crate::stats::unread_counts,
        crate::stats::processing_count,
        crate::stats::badge_stats,
        crate::stats::long_form_stats,
        crate::refresh::refresh_token,
        crate::account_deletion::delete_current_account,
        crate::admin_api_keys::api_keys_page,
        crate::admin_api_keys::create_key,
        crate::admin_api_keys::revoke_key,
        crate::admin_auth::login_page,
        crate::admin_auth::login,
        crate::admin_auth::logout,
        crate::admin_logs::list_logs,
        crate::admin_logs::view_log,
        crate::admin_logs::download_log,
        crate::admin_logs::errors_dashboard,
        crate::admin_logs::reset_error_logs,
        crate::admin_onboarding::preview_page,
        crate::admin_onboarding::preview,
        crate::admin_pages::dashboard,
        crate::admin_pages::feedback,
        crate::admin_pages::vendor_usage,
        crate::admin_pages::legacy_llm_usage,
        crate::apple_auth::apple_sign_in,
        crate::cli_link::start_link,
        crate::cli_link::approve_link,
        crate::cli_link::poll_link,
        crate::debug_auth::debug_create_user,
        crate::scraper_configs::list_scraper_configs,
        crate::scraper_configs::create_scraper_config,
        crate::scraper_configs::update_scraper_config,
        crate::scraper_configs::delete_scraper_config_endpoint,
        crate::scraper_configs::list_content_scraper_configs,
        crate::scraper_configs::create_content_scraper_config,
        crate::scraper_configs::update_content_scraper_config,
        crate::scraper_configs::delete_content_scraper_config_endpoint,
        crate::scraper_configs::subscribe_to_feed,
        crate::scraper_configs::subscribe_content_to_feed,
        crate::users::get_current_user,
        crate::users::update_current_user
    ),
    components(schemas(
        ErrorEnvelope,
        HealthResponse,
        HealthChecks,
        HealthStatus,
        BriefingTier,
        BriefingFirstRunPhase,
        BriefingFirstRunSourceOutcome,
        BriefingRunKind,
        BriefingBlockType,
        BriefingFigurePlacement,
        BriefingFigureAlignment,
        BriefingLensSummary,
        BriefingFirstRunSourceProgress,
        BriefingFirstRunProgress,
        BriefingIndexResponse,
        BriefingRunDto,
        BriefingParagraphDto,
        BriefingBlockDto,
        BriefingSegmentDto,
        BriefingDiscussionDto,
        BriefingSourceDto,
        BriefingLensResponse,
        BriefingReadMarkRequest,
        BriefingReadMarkResponse,
        BriefingDigSearchRequest,
        BriefingDigSearchResult,
        BriefingDigSearchResponse,
        BriefingDigSummarizeRequest,
        BriefingDigSummarizeResponse,
        BriefingNarrationRequest,
        AudioEpisodeKind,
        AudioEpisodeStatus,
        AudioEpisodeResponse,
        AudioEpisodeDelivery,
        CustomNarrationCreateRequest,
        AudioEpisodeShareResponse,
        BriefingNarrationResponse,
        BriefingRefreshResponse,
        JobStatusResponse,
        ContentClassification,
        SummaryKind,
        SummaryVersion,
        TaskType,
        TaskStatus,
        NewsItemVisibilityScope,
        NewsItemStatus,
        SavedSource,
        PaginationMetadata,
        LlmProvider,
        MessageProcessingStatus,
        ChatMessageRole,
        ChatMessageDisplayType,
        FeedFormat,
        FeedType,
        AssistantFeedOption,
        CouncilCandidate,
        CouncilStartRequest,
        CouncilSelectRequest,
        CouncilRetryRequest,
        CreateChatSessionRequest,
        UpdateChatSessionRequest,
        SendChatMessageRequest,
        AssistantScreenContextDto,
        AssistantTurnRequest,
        ChatMessageDto,
        ChatSessionSummaryDto,
        ChatSessionDetailDto,
        ChatSessionListResponse,
        CreateChatSessionResponse,
        SendMessageResponse,
        AssistantTurnResponse,
        ChatToolProgressDto,
        MessageStatusResponse,
        DetectedFeed,
        ContentSummaryBulletPoint,
        ContentSummaryQuote,
        ContentSummaryResponse,
        ContentListResponse,
        ContentDetailResponse,
        NewsItemSummaryResponse,
        NewsItemListResponse,
        NewsItemDetailResponse,
        ContentBodyResponse,
        ChatGptUrlResponse,
        ConvertNewsResponse,
        ConvertNewsItemResponse,
        DownloadMoreRequest,
        DownloadMoreResponse,
        NarrationTargetType,
        NarrationResponse,
        TweetLength,
        TweetSuggestion,
        TweetSuggestionsRequest,
        TweetSuggestionsResponse,
        SubmissionKind,
        SubmissionOutcome,
        SubmissionFeedInitialDownloadResponse,
        SubmissionFeedSubscriptionResponse,
        SubmissionContentResult,
        SubmissionFeedSubscriptionResult,
        SubmissionLearningDeckResult,
        SubmissionNoActionResult,
        SubmissionResult,
        SubmissionStatusResponse,
        SubmissionStatusListResponse,
        PodcastEpisodeSearchResultResponse,
        PodcastEpisodeSearchResponse,
        MixedSearchFeedResultResponse,
        MixedSearchResponse,
        DiscussionMode,
        DiscussionLinkResponse,
        DiscussionCommentResponse,
        DiscussionItemResponse,
        DiscussionGroupResponse,
        DiscussionSummaryTopicResponse,
        DiscussionSummaryLinkResponse,
        DiscussionSummaryCommentResponse,
        DiscussionSummaryResponse,
        ContentDiscussionResponse,
        LearningDeckSourceKind,
        LearningDeckRunStatus,
        LearningDeckStatus,
        LearningDeckCreateRequest,
        LearningDeckTimelineEntry,
        LearningDeckRunResponse,
        LearningDeckResponse,
        LearningDeckListResponse,
        LearningDeckUrlResponse,
        LearningDeckShareResponse,
        AudioTranscriptionHealthResponse,
        AudioTranscriptionResponse,
        LlmTaskActionStatus,
        LlmTaskApprovalPolicy,
        LlmTaskActionResponse,
        LlmTaskActionListResponse,
        LlmTaskActionRejectRequest,
        LlmTaskMode,
        LlmTaskStatus,
        ShareActionCreateRequest,
        ShareActionResponse,
        UserResponse,
        UpdateUserProfileRequest,
        CouncilPersonaConfig,
        CouncilPersonaInput,
        ReadingExperience,
        OperationStatus,
        SubmitFeedbackRequest,
        SubmitFeedbackResponse,
        ContentInteractionType,
        RecordContentInteractionRequest,
        RecordContentInteractionResponse,
        BulkMarkReadRequest,
        BulkMarkReadResponse,
        MarkReadResponse,
        MarkUnreadResponse,
        KnowledgeMutationStatus,
        KnowledgeMutationResponse,
        ContentType,
        ContentStatus,
        SubmitContentRequest,
        ContentSubmissionResponse,
        UnreadCountsResponse,
        ProcessingCountResponse,
        BadgeStatsResponse,
        LongFormStatsResponse,
        RefreshTokenRequest,
        AccessTokenResponse,
        AppleSignInRequest,
        TokenResponse,
        DebugUserSessionRequest,
        DeleteAccountRequest,
        DeleteAccountResponse,
        CliLinkStatus,
        CliLinkStartRequest,
        CliLinkStartResponse,
        CliLinkApproveRequest,
        CliLinkApproveResponse,
        CliLinkPollResponse,
        ApiKeyCreateResponse,
        ApiKeySummaryResponse,
        AdminLoginRequest,
        AdminLoginResponse,
        AgentLibraryDocumentVariant,
        AgentLibraryDocumentResponse,
        AgentLibraryManifestResponse,
        AgentLibraryFileResponse,
        AgentSearchResultKind,
        AgentSearchRequest,
        AgentSearchResultResponse,
        AgentSearchResponse,
        ScraperType,
        CreateUserScraperConfig,
        UpdateUserScraperConfig,
        SubscribeToFeedRequest,
        FeedSubscriptionOutcome,
        ScraperConfigStatsResponse,
        ScraperConfigResponse,
        OnboardingSuggestionType,
        OnboardingSuggestion,
        OnboardingFastDiscoverResponse,
        OnboardingProfileRequest,
        OnboardingProfileResponse,
        OnboardingVoiceParseRequest,
        OnboardingVoiceParseResponse,
        OnboardingAudioDiscoverRequest,
        OnboardingAudioDiscoverResponse,
        OnboardingAudioLaneTarget,
        OnboardingAudioLanePreview,
        OnboardingAudioLanePreviewResponse,
        OnboardingFastDiscoverRequest,
        OnboardingSelectedAggregator,
        OnboardingCompleteRequest,
        OnboardingCompleteResponse,
        AgentOnboardingStartRequest,
        AgentOnboardingStartResponse,
        AgentOnboardingCompleteRequest,
        OnboardingDiscoveryLaneStatus,
        OnboardingDiscoveryStatusResponse,
        OnboardingTutorialResponse
        ,UserLlmProvider,
        UserLlmIntegrationResponse,
        UpsertUserLlmIntegrationRequest,
        UserLlmIntegrationTestResponse,
        DeleteStatus,
        DeleteUserLlmIntegrationResponse,
        XOAuthStartRequest,
        XOAuthStartResponse,
        XOAuthExchangeRequest,
        XConnectionResponse,
        IntegrationDisconnectStatus,
        IntegrationDisconnectResponse
    )),
    modifiers(&SecurityAddon),
    tags(
        (name = "operations", description = "Runtime health and readiness"),
        (name = "agent", description = "Machine-oriented agent API"),
        (name = "briefing", description = "Authenticated Briefing reading and narration workflows"),
        (name = "content", description = "Authenticated content workflows"),
        (name = "integrations", description = "Authenticated external provider connections"),
        (name = "learning", description = "Authenticated Learning Deck workflows"),
        (name = "news", description = "Authenticated short-form news workflows"),
        (name = "onboarding", description = "Authenticated onboarding workflows"),
        (name = "scrapers", description = "Authenticated source scraper configuration")
        ,(name = "share-actions", description = "Authenticated ShareSheet action workflows")
    )
)]
struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "HTTPBearer",
                SecurityScheme::Http(Http::new(HttpAuthScheme::Bearer)),
            );
        }
    }
}

async fn openapi() -> Json<utoipa::openapi::OpenApi> {
    Json(document())
}

pub(super) fn document() -> utoipa::openapi::OpenApi {
    crate::wire_presence::normalize_response_presence(ApiDoc::openapi())
}
