-- Generated by scripts/generate_runtime_ownership_route_seeds.py. Do not edit manually.
-- Never erase a row that has been transitioned or operator-modified.
DELETE FROM runtime_ownership
WHERE resource_kind = 'route_group'
  AND active_owner = 'python'
  AND active_version = 1
  AND desired_owner IS NULL
  AND desired_version IS NULL
  AND transition_state = 'active'
  AND updated_by = 'sqlx-route-seed'
  AND NOT EXISTS (
      SELECT 1
      FROM runtime_ownership_audit AS audit
      WHERE audit.resource_kind = runtime_ownership.resource_kind
        AND audit.resource_key = runtime_ownership.resource_key
  );
